\pagenumbering{arabic}

\setcounter{secnumdepth}{3}

\part{Introduktion og litterært overblik}

# Indledning
Denne afhandling har til formål at undersøge langsigtet investering i aktiver under antagelsen om periodisk rebalancering. Dette gøres ved anvendelse af den analytiske løsning, til det dynamiske porteføljeproblem, først beskrevet af [@JurVic2011]. Denne løsning anvendes for en institutionel investor med endelig investeringshorisont, tidsvarienede investeringsmuligheder og under antagelsen om potens nytte, *CRRA*, som er defineret over deres intertemporale budget constraint. Sættet af tidsvarierende investeringsmuligheder er konstante under hele investeringshorisonten, dette tillader at vi kan lave sammenligning af investorer med en kort og langinvesteringshorisont samt for forskellige risiko tolerancer. Investeringssættet, som spænder fra 1960 1. kvartal til 2014 4 kvartal, består af en 90-dages amerikansk *T-Bill* -- som samtidig repræsenterer benchmark aktivet -- et aktieindeks, som repræsenterer samtlige aktier handlet på *NYSE*, *AMEX* og *NASDAQ*, den 10-årige amerikanske statsobligation samt et virksomhedsbaseret obligationsindeks. Før modellering af merafkastene på ovenstående aktiver undersøges prædiktabiliteten af afkastene ved benyttelse af de oftest anvendte variable, som før har vist prædiktablitetsegenskaber i litteraturen. Selve modellering af tilstandsvariablene antages at følge en første-ordens *Vector Autoregressive Process*. Analysen  viser at bm, yield spread og ??, udviser størst statistisk signifikans. Derudover findes der evidens for, at afkastene på de risikobærende aktiver specielt er tidsvarierende. Afkastet på aktieindekset viser sig, at være sværest prædiktabelt, mens stats- og virksomhedsobligationerne bevæger sig procyklisk med yield spread. Porteføljevalget for investoren afhænger kraftigt af disse afkastbevægelser, da han udnytter denne information til at lave periodiske reblancereringer ift. sin risikoaversion. Ved undersøgelse af både investeringshorisontlængdens effekt, risiko tolerancer og betydningen af kortsalg kan vi effektivt måle forskellen mellem en lang type investorer.

## Problemformulering
Ved analytisk behandling af det dynamiske portefølje problem, vil denne afhandling undersøge, hvordan porteføljeallokeringer adskiller sig: på tværs af investeringshorisonter, ved kortsalgs restriktioner og ved forskellige tolerancer for risiko.

\begin{center}
\textit{Hvordan adskiller porteføljeallokeringen sig over investeringshorisonter, for den institutionelle og/eller private investor, under antagelsen, at der er mulighed for periodisk rebalancering?}
\end{center}

De underliggende spørgsmål som ligger i forlængelse af det ovenstående grundlæggende spørgsmål, vil undervejs i afhandlingen ligeledes blive behandlet og undersøgt, heriblandt, hvordan risikotolerancer hos individuelle investorer påvirker allokeringen mellem risikobærende aktiver.

## Afgrænsning
Denne afhandling forsøger at svare ovenstående hovedspørgsmål ved benyttelse af empirisk data. I forlængelse af søgen efter et sådan svar, vil en teoretisk afgrænsning være nødvendig. Menneskelig kapital samt forbrug vil af den grund ikke være en del af den empiriske analyse. Dette er også ensbetydende med at budgetbegrænsningen for hver institutionelle og/eller private investor er fuldstændig fastsat ud fra deres finansielle formue.

Investorerne antages at have deres nytte defineret via *CRRA*-nytte. For at anvende *CRRA*-nytte i porteføljeproblemet benyttes modellen fra [@JurVic2011], som er defineret i diskrettid, med approksimative analytiske løsninger. Dette medfører bl.a. at porteføljevalget i kontinuert tid bliver tilsidesat, da hovedformålet med afhandlingen er at undersøge det langsigtede portefølgevalg på forskellige tidspunkter over investorens investeringshorisont. Derudover ville en kontinuert behandling af det dynamiske porteføljeproblem ligeledes kræve en diskretisering af observationsrummet for anvendelse i et analytisk empirisk øjemed. Ved anvendelse af den teoretiske ramme foreslået af [@JurVic2011] antages det samtidigt, at investorens nytte kun er defineret over hans budgetbegrænsning og over en fastlagt investeringshorisont med tidsvarierende investeringsmuligheder, som er modelleret via en VAR$(1)$-process.

In sample bla. Data bla.

Transaction costs.

En analyse af kortsalgsrestriktion på porteføljeproblemet er ligeledes medtaget i afhandlingen, men omkostningerne ved lån/gearing af den optimale portefølje er udeladt.

## Eksisterende litteratur

En langsigtet porteføljestrategi forsøger at optimere bytteforholdet mellem risiko og afkast. En sådan strategi er i sagens natur optimal på lang sigt og ikke nødvendigvis på kort sigt. Den moderne teori bag dette bytteforhold, for den langsigtede investor, blev først beskrevet af Nobelpris modtageren Harry Markowitz, [@Markowitz1952]. Hans arbejde tager udgangspunkt i en investor på tidspunkt $t$, som kun bekymrer sig om fordelingen af sin formue på et givet fremtidigt tidspunkt $t+K$, hvor $K$ er investeringshorisonten. Dette problem bliver undertiden beskrevet som det statiske portefølje problem. [@Markowitz1952] understreger vigtigheden af diversifikation af risiko, men den bærende antagelse om en køb og hold investor, findes særdeles urealistisk. Investorer vælger ofte porteføljestrategier, som kræver rebalancering før eller siden og er på den måde dynamiske i deres strategi.

Mere generelt vil investorer altså rebalancere deres portefølje mellem tidspunkt $t$ og $t+K$, på en måde, som forholder sig til skiftende finansielle, demografiske og makroøkonomiske forhold over tid. Investoren vil altså i dette tilfælde vælge en dynamisk porteføljestrategi, som specificerer, hvordan allokeringen af en eller flere aktiver skal ændres i respons til de tidsafhængige bagvedliggende variable.

Dynamisk programmering er blevet brugt i litteraturen til at formulere en løsning, [@Samuelson1969] og [@Merton1969; @Merton1971; @Merton1973]. Udover de specialtilfælde, hvor den langsigtede porteføljestrategi består af en række optimale kortsigtede strategier, er ingen generel løsning på lukket form udledt, [@JurVic2011]. [@Samuelson1969] introducerer også en model, som medtager forbrugsfunktionen. [@Merton1969] beskriver den dynamiske allokering i kontinuert tid til forskel fra de tidligere diskrettidsmodeller af bl.a. [@Samuelson1969]. Derudover beskriver [@Merton1969], hvordan en flerdimensional stokastisk model -- hvor de underliggende variable er modelleret via en Wiener process -- giver en rigere og mere alsidig model.

På baggrund af det svære løsningsproblem, var der over længere tid en faldende interesse for emnet, men nylig videnskabelig litteratur af finansielle økonomer har atter kastet lys på emnet. Disse foreslår alternative løsningsmetoder for det langsigtede porteføljeproblem med rebalancering, og har igen fundet eksakte analytiske løsninger for yderligere specialtilfælde, i kontinuert tid, end de tidligere beskrevne. Ved antagelse af en konstant risikofri rente og modellering af merafkastet gennem en Ornstein-Uhlenbeck process finder [@BrenXia2002], [@CampVic1999], [@KimOm1996] og [@Wachter2002] løsninger på lukket form for en lang række nyttefunktioner, heriblandt power utility over forbrug, power utility over terminal nytte og for Epstein-Zin utility med intertemporal substitutionselasticitet lig én, [@CampVic2003].

Derudover er numeriske metoder blevet foreslået af bl.a. [@BalLyn1999], [@Lyn2001], [@Bar2000], [@BrenSchLag1997; @BrenSchLag1999], hvor de anvendte modeller enten har diskretiseret observationsrummet eller fundet numeriske løsninger til den partielle differential ligning hørende til det dynamiske problem. Disse -- til tider advancerede -- numeriske metoder har dog vist sig at være svært anvendelige, i praksis har det været komplekst at implementere selv for få variable.

Ovenstående modeller tillader ikke den risikofrie rente og merafkastet af aktiver at ændre sig over tid, på samme tid, og mangler dermed det tidsvarierende perspektiv af alle aktiver. En ny metode præsenteret af [@CampVic2003], giver approksimative analytiske metoder i et ikke-tilfældigt nabolag af specialtilfælde, hvor løsninger på lukket form er mulige. Her tager de udgangspunkt i en investor, som opnår nytte af forbrug i stedet for formue. [@CampVicCha2003] benytter samme metode til et problem involverende flere risikofyldte aktivklasser, hvor de samtidig tillader tidsvarierende investeringsmuligheder.

Mit arbejde vil være en validering af [@JurVic2011] ved anvendelse af deres teori samt analytiske løsninger til det dynamiske porteføljeproblem for en privat investor med et opdateret datagrundlag. Jeg bidrager til det dynamiske porteføljeproblem ved en længere statistisk analyse af potentielle variable, som kan benyttes til det prædiktive afspekt af flere aktivers afkast.

## Opbygning samt tekniske specifikationer
Opbygningen af denne afhandling tager udgangspunkt i dele. Første del fungerede som en introduktion til litteraturen og afhandlingens formål. I Del 2 ?? af afhandlingen fastlægges det teoretiske fundament. Kapitel 3 ?? giver et overblik over den underlæggende porteføljeteori for en institutionel investor. Kapitel 4 ?? afkast... . Kapitel 5 ?? bygger videre fra teorien i Kapitel 3 ?? og medtager rebalanceringsperspektivet. Kapitel 6 ?? opbygger VAR-processen i for vores investeringssæt. Del 3 ?? består af den empiriske analyse, hvor teorien fra Del 2 ?? benyttes på virkeligt data. Kapitel 7 ?? beskriver data samt kilder. Kapitel 8 ?? består af univariate- og multivariate regressioner, som benyttes til udvælgelse af variable med bedste prædiktabilitetsegenskaber til den endelige VAR-model. Kapitel 9 ?? har til formål at præsentere et overblik over den endelige VAR-model. Kapitel 10 ?? foretager analysen af samtlige porteføljeallokeringer. Kapitel 11 ?? indeholder en diskussion og reflektion over fundende i Kapitel 10 ??. Til slut afslutter Kapitel 12 ?? afhandlingen med en konklusion. 

Databehandling samt modelestimation er beregnet og kodet via statistikprogrammet **R** 3.6.0 *"Planting of a Tree"*. Teoretisk dokumenterede **R**-pakker er anvendt ved estimation af VAR-processen samt for de univariate- og multivariate regressioner, for yderligere information henvises til dokumentationen i litteraturlisten.
\newpage