\part{Den teoretiske ramme}

# Underliggende teori {#unteo}

I dette kapitel introduceres den underliggende teori til det dynamiske porteføljeproblem: det statiske porteføljeproblem. Derudover defineres en række nyttefunktioner, som alle er defineret over terminalformue. Sektion \@ref(myoinv) starter med en gennemgang af porteføljeproblemet for den myopiske investor, som først blev introduceret af [@Markowitz1952]. Dernæst fungerer Sektion \@ref(preforris) som en introduktion til risikoaversion. Sektion \@ref(nytdefover) belyser en række nyttefunktioner, som alle kan fungere i porteføljemodellering. Fordelingsmæssige resultater vedr. afkast tages hånd om i Sektion \@ref(fordafafk). Slutteligt opsummerer Sektion \@ref(opsunteo) kapitlets fund. 

## Den myopiske investor{#myoinv}
Den myopiske investor vælger -- som navnet ligger op til -- sin portefølje under et én-periodes perspektiv, og foretager dermed et statisk bindende valg. Investoren forsøger at maksimere sin terminal formue, ved samtidig at forholde sig til sin risikoaversion. Dette forårsager, at alle efterfølgende perioder bliver ignoreret af investoren. Ergo skal han løse det statiske portefølje problem fra tidspunkt $t$ til tidspunkt $t+1$. I denne ene periode antages investeringsmulighederne at være: et risikobærende aktiv samt et risikofrit aktiv. Afkastene over den førstkommende periode for disse aktivklasser vil blive noteret som hhv. $R_{t+1}$ med betinget middelværdi $\mathbb{E}_t\left[R_{t+1}\right]$^[Her benyttes den gængse notation $\mathbb{E}\left[R_{t+1}\mid \mathcal{F}_t\right]=\mathbb{E}_t\left[R_{t+1}\right]$ for filteret $\mathcal{F}_t$.] samt betinget varians $\mathbb{V}_t\left[R_{t+1}\right]=\sigma_t^2$ og $R_{0,t+1}$.

Det antages at investorens formue er fuldt allokeret, når en del $\alpha_t$ bliver placeret i det risikobærende aktiv og $(1-\alpha_t)$ i det risikofrie aktiv. Hermed bliver hans porteføljeafkast givet ved
\begin{equation}
R_{p,t+1}=\alpha_t R_{t+1}+\left(1-\alpha_t\right)R_{0,t+1}.(\#eq:Portafk)
\end{equation}

Den betingede middelværdi af porteføljeafkastet bliver dermed
\begin{align}
\mathbb{E}_t\left[R_{p,t+1}\right]&=\alpha_t\mathbb{E}_t\left[R_{t+1}\right]+(1-\alpha_t)R_{0,t+1} \notag\\ 
&=R_{0,t+1}+ \alpha_t\left(R_{t+1} - R_{0,t+1}\right),(\#eq:Forvport)
\end{align}

og endeligt den betingede varians af porteføljeafkastet
\begin{equation}
\mathbb{V}_t\left[R_{p,t+1}\right]=\alpha_t^2\sigma_t^2.(\#eq:Varport)
\end{equation}

Den simplificerene antagelse i [@Markowitz1952] er, at investorer kun forholder sig til de første to momenter, hvis vi modellerer denne afvejning lineært, opnår vi følgende maksimeringsproblem
\begin{equation}
\max_{\alpha_t} \mathbb{E}_t\left[R_{p,t+1}\right] -\frac{k}{2} \mathbb{V}_t\left[R_{p,t+1}\right],(\#eq:Statmaks)
\end{equation}

hvor $k$ er en skalering, som repræsenterer investorens risikoaversion. Ved at modellere ovenstående relation som lineær og kun afhængig af de første to momenter restringeres investoren til at foretrække et højt afkast, lav volatilitet og ignorerer alle højere momenter, såsom skævhed og kurtosis. Ved indsættelse af Ligning \@ref(eq:Portafk) i Maksimeringsproblemet \@ref(eq:Statmaks) og dernæst første ordens differentiation, opnås førsteordensbetingelsen, se evt. Appendiks \@ref(udlmyo). Løsningen til optimalitetsproblemet bliver
\begin{equation}
\alpha_t = \frac{\mathbb{E}_t\left[R_{t+1}\right]-R_{0,t+1}}{k\sigma_t^2}.(\#eq:Løsning)
\end{equation}

Porteføljeanalyse benytter ofte nøgletallet *Sharpe Ratio*, også kendt som *Market Price of Risk* i stokastisk finansiering, [@Bjork2009]. I porteføljeteori er det kendt som et performance-mål, som fortæller investoren om merafkastet i sin portefølje relativt til den risiko han har påtaget sig, altså
$$S_t=\frac{\mathbb{E}_t\left[R_{t+1}\right]-R_{0,t+1}}{\sigma_t}.$$

Dette tillader, at vi kan omskrive Ligning \@ref(eq:Løsning) til
$$\alpha_t=\frac{S_t}{k\sigma_t}.$$

Forholdet mellem middelværdien og variansen er $\tfrac{1}{k}$, eftersom vi kan udlede, at merafkastet på porteføljen er $\tfrac{S_t^2}{k}$ og variansen er $\tfrac{S_t^2}{k^2}$. *Sharpe Ratio*'en på porteføljen er $S_t$, og alle tænkelige porteføljer (afhængig af $k$) vil have samme *Sharpe Ratio*, fordi de er eksponeret til det risikobærende aktiv, men i stadig større eller mindre grad.

Altså er vægtningen i det risikobærende aktiv et forhold mellem: det forventede risikobærende merafkast over det risikofrie aktiv samt en skalering af det risikobærende aktivs varians. Vi kan uden problemer opskrive ovenstående løsning til tilfældet, hvor investoren står overfor $n>1$ risikobærende aktiver. $\bm{R}_{t+1}$ repræsenterer en $n\times 1$ vektor af afkast for risikobærende aktiver, fra $t$ til $t+1$. Den betingede middelværdi bliver $\mathbb{E}_t\left[\bm{R}_{t+1}\right]$ og den betingede kovariansmatrix noteres som $\mathbb{V}_t\left[\bm{R}_{t+1}\right]=\bm{\Sigma}_t$. Herudover er $\bm{\alpha}_t$ nu en $n\times 1$ vektor af vægte i de risikobærende aktiver.

Den betingede middelværdi af porteføljeafkastet bliver dermed nu
\begin{equation*}
\mathbb{E}_t\left[R_{p,t+1}\right]=R_{0,t+1}+\bm{\alpha}_t'(\mathbb{E}_t\left[\bm{R}_{t+1}\right]- R_{0,t+1}\bm{\ell}),
\end{equation*}

den betingede varians af porteføljeafkastet bliver
\begin{equation*}
\mathbb{V}_t\left[R_{p,t+1}\right]=\bm{\alpha}_t'\bm{\Sigma}_t\bm{\alpha}_t.
\end{equation*}

Nu kan maksimeringsproblemet opskrives
\begin{equation}
\max_{\alpha_t} \bm{\alpha}_t'(\mathbb{E}_t\left[\bm{R}_{t+1}\right]- R_{0,t+1}\bm{\ell}) - \frac{k}{2}\bm{\alpha}_t'\bm{\Sigma}_t\bm{\alpha}_t, (\#eq:MultStatmaks)
\end{equation}

Den optimale porteføljestrategi, givet som løsningen til Maksimeringsproblemet \@ref(eq:MultStatmaks) findes til at være
\begin{equation}
\bm{\alpha}_t=\frac{1}{k}\bm{\Sigma}_t^{-1}(\mathbb{E}_t\left[\bm{R}_{t+1}\right]-R_{0,t+1}\bm{\ell}).(\#eq:Multalpha)
\end{equation}

Løsningen er en generalisering af Ligning \@ref(eq:Løsning). Derudover er det værd at bemærke, at løsningen er karakteriseret af \textit{The Mutual Fund Seperation Theorem}, [@Tobin1958], som var en af mange videnskabelige bidrag James Tobin fik sin Nobelpris for i 1981, [@Nobel2020]. Essencen af Sætningen er, at alle investorer vil holde den eksakt samme portefølje af risikobærende aktiver samt en del i det risikofrie aktiv. Det eneste som adskiller investorer fra hinanden, er deres relative fordeling af total formue i den optimale risikobærende portefølje, som er fastsat ud fra deres egne risikopræferencer. Figur \@ref(fig:AfkVol) viser de optimale porteføljestrategier i et afkast-volatilitets spektrum.

\begin{figure}[H]
\centering
\begin{tikzpicture}[scale=1]
\begin{axis}[
  xticklabel={$\pgfmathprintnumber{\tick}\,\%$},
  yticklabel={$\pgfmathprintnumber{\tick}\,\%$},
  height=7cm, width=12cm,
  axis x line=bottom, axis y line=left,
  xlabel = Standardafvigelse, ylabel = Forventet afkast,
  ymin=0, ymax=25, xmin=0, xmax=60,
  extra x ticks={65}, extra x tick labels={$\sigma$},
  extra x tick style={major tick length=0mm, grid=none},
  extra y ticks={27}, extra y tick labels={$\mu$},
  extra y tick style={major tick length=0mm, grid=none},
  enlargelimits=true,
  scatter/classes={
    a={mark=o,draw=black, mark size = 3pt},
    b={mark=*, mark size = 3pt,draw=red, fill = red},
    c={mark=*, mark size = 3pt,draw=black, fill = black}
  }
]

\addplot[scatter,only marks, scatter src=explicit symbolic]
  coordinates {
    (30, 11)     [c]
    (19, 5)      [c]
    (40, 15)     [c]
    (16, 10)     [b]
  };
\node at (axis cs:19, 5) [anchor=north west] {Aktiv 1};
\node at (axis cs:30,11) [anchor=north west] {Aktiv 2};
\node at (axis cs:40,15) [anchor=north west] {Aktiv 3};
\addplot[red, very thick,  domain=-1:2.5, samples=200, variable=\t](
   {(20^2*t^2 + 12^2*(1-t)^2)^(0.5) }, %{(t^2 * 20^2 + (1-t)^2 * 12)},
   {11 * t + (1-t) * 5}
 );
\node[color=red] at (axis cs:30, 0) [anchor=south west] {\textbf{Den efficiente rand}};
\addplot[black, very thick, domain=-10:50, samples=100, variable=\x](
  ({x}, {4 + 0.37 * x});
\node[rotate = 25, color=black] at (axis cs:30, 15) [anchor=south west] {\textbf{CML}};
\node[pin={[pin edge={thick}, text width=3cm, pin distance=2cm]90:{{\centering Tangensporteføljen}}}] at (axis cs:16, 10.5) {};
\end{axis}
\end{tikzpicture}
\caption{Afkast-volatilitets spektrummet.}
\label{fig:AfkVol}
\end{figure}

Altså vil investorer vælge en portefølje på den efficiente rand, som opnår en efficient porteføljevægtning langs *Capital Market Line*. Derudover skal det nævnes, at det kun er den øvre halvdel af den efficiente rand, som reelt set er efficient. Dette kommer sig af at porteføljer på den nederste del har en identisk påhæftet volatilitet, men med et lavere forventet afkast end den symmetrisk modsatte portefølje.

Selvom Markowitz' model er en hjørnesten inden for moderne porteføljeteori, er der flere mangler i den opsatte teoretiske ramme. Først og fremmest medfører Markowitz' antagelse om en lineær afvejning mellem kovarianser og afkast implicit antagelsen, at investorenes nyttefunktioner kan approksimeres af en anden ordens Taylor udvidelse over en bredt spektrum af afkast. Derudover findes ingen beskrivelse for, hvordan parameteren $k$ er koblet til investorens nyttefunktion. Disse mangler kan blive afhjulpet ved samtidig brug af specifikke nyttefunktioner og afkastfordelinger, som opfylder Taylor udvidelsen. Dette medfører at middelværdi-varians analysen kan benyttes for tre forskellige opsætninger, som bliver præsenteret i Sektion \@ref(typnyt), [@CampVic2003].

## Præferencer for risiko {#preforris}
For et fast formueniveau $w\in \mathbb{R}_+$ betragter vi en stokastisk variabel $X$, hvor $\mathbb{E}(X)=0$. Derfor kan også $w+X$ betragtes som en stokastisk variabel, der repræsenterer en fremtidig formueplan med realiseret formue $w+\mathbb{E}(X)$, hvis $X$ bliver realiseret. Derfor kaldes $X$ undertiden også et fair spil, derudover haves at $\mathbb{E}(w+X)=w$.

En (strengt) risikoavers investor vil for alle $w\in \mathbb{R}_+$ og alle $X$ (strengt) foretrække den sikre formue $w$ fremfor $w+X$. Ergo vil investoren altid afslå ethvert fair spil. Omvendt vil en (strengt) risikoelskende investor foretrække spillet og dermed $w+X$ fremfor $w$. Endeligt findes risikoneutrale investorer, som er indifferent mellem den sikre formue $w$ og formuen $w+X$. I realiteten er investorer ingen af delene, f.eks. vil nogle afslå fair spil i et ikke-tilfældigt nabolag rundt om værdien af $w$. Dette betegnes undertiden som at være lokalt risikoavers, lokalt risikoelskende og lokalt risikoneutral.

Generelt anses investorer (og andre individer for den sags skyld) at være risikoaverse, derfor vil fokus være på denne risikopræference.

## Nytte defineret over formue {#nytdefover}

I Sektion \@ref(myoinv), blev en af de bærende antagelser i [@Markowitz1952] introduceret: at investorer kun forholder sig til middelværdien og variansen af porteføljeafkast, og ikke højere momenter. Det kan tilsvarende antages, at investorer definerer deres nytte via formue på terminaltidspunktet. Dette tillader at redefinere Maksimeringsproblemet \@ref(eq:Statmaks) til nedenstående
\begin{align}
&\max\mathbb {E}_t\left[U(W_{t+1})\right] (\#eq:Nyttemaks)\\
&\text{ubb.}\,\,W_{t+1}=(1+R_{p,t+1})W_t.\notag
\end{align}

Hvor $U(W_{t+1})\in\mathbb{R}_+$ er en konkav nyttefunktion. Investoren vil givet nyttefunktionens konkave krumning være risikoavers. Netop dette aspekt gør, at vi kan inkorporere risikoaversion, når investorens porteføljevalg skal foretages. For at fastlægge denne investorspecifikke risikoaversion benyttes derfor skalerede krumningsmål. Disse fundamentale risikoaversionsmål er kendt som *Arrow-Pratt Målene for Risikoaversion*, [@Arrow1965] og [@Pratt1964]. Når nytte skal belyses, kan risikoaversion mht. den fremtidige formue $W_{t+1}$ benyttes. Graden af krumningen på nyttefunktionen giver information om investorens risikopræferencer introduceret ovenfor. Det antages at investorens nyttefunktion er strengt voksende i terminal formue -- altså er investoren grådig og foretrækker høj formue frem for en lav formue -- men i en faldende rate. Nyttefunktion vil altså have følgende karakteristika
$$U'(W)>0\quad\text{og}\quad U''(W)<0.$$

Hvor $U'(W)$ og $U''(W)$ er de hhv. første og anden afledte mht. formuen $W$. Når denne risikoaversion skal kvantificeres, skal det sikres, at målet er invariant overfor strengt positive affine transformationer. Dette er bl.a. opfyldt ved brug af *Coefficient of Absolut Risk Aversion*, [@Arrow1965] og [@Pratt1964]. *ARA* er defineret som den negative anden afledte af nyttefunktionen mht. formue, skaleret med den første afledte
$$\text{ARA}(W)=-\frac{U''(W)}{U'(W)}.$$

Selvom den anden afledte af nyttefunktionen er et mål for krumningen af nyttefunktionen, er det nødvendigt at skalere for at eliminere afhængigheden af abitrære størrelser, som relaterer sig til målbarheden af nytte. *ARA* måler investorens absolutte dollar værdi, som han er villig til at købe, for at undgå et tab på samme absolutte størrelse. Hvis *ARA* er faldende medfører det, at desto mere formue en investor har, desto mere risikosøgende bliver han, altså haves at $\text{ARA}(W)<0$, og så fremdeles. Almindeligt menes det, at *ARA* burde falde, eller i det mindste ikke stige, med formue. Et relateret mål er *Coefficient of Relative Risk Aversion*, *RRA*, som er samtidig tager højde for investorens formue
$$\text{RRA}(W)=-\frac{WU''(W)}{U'(W)}.$$

Her måles marginal nytten og dermed investorens risikoaversion over en procentdel af formuen. Samme inferens som for *ARA* kan blive udtænkt for *RRA*. *RRA* måler den del af formuen, som investoren vil betale for at undgå et spil på en given størrelse relativt til formuen.

De tilsvarende reciprokke af ovenstående mål kaldes hhv. *Coefficeint of Absolute Risk Tolerance* samt *Coefficeint of Relative Risk Tolerance*.

\begin{figure}[H]
\centering
\begin{tikzpicture}[scale=1]
\begin{axis}[
  height=7cm, width=12cm,
  axis x line=bottom, axis y line=left,
  xlabel = Formue, ylabel = Nytte,
  ymin=0, ymax=25, xmin=0, xmax=60,
  xtick={5, 15, 30}, xticklabels={$W_{t}-G$, $W_t$, $W_t+G$},
  ytick={9.7, 16.3, 20.5}, yticklabels={$U(W_{t}-G)$, $U(W_{t})$, $U(W_{t}+G)$},
    extra x ticks={65}, extra x tick labels={$W_{t+1}$},
  extra x tick style={major tick length=0mm, grid=none},
  extra y ticks={27}, extra y tick labels={$U(W_{t+1})$},
  extra y tick style={major tick length=0mm, grid=none},
  enlargelimits=true,
]
\addplot[black, very thick, smooth, domain=-10:50, samples=100, variable=\x](
  ({x}, {6*ln(\x)});
  \draw [dashed] (5,-2.5) -- (5,9.7);
  \draw [dashed] (-6,9.7) -- (5,9.7);
  
  \draw [dashed] (15, -2.5) -- (15, 16.3);
  \draw [dashed] (-6, 16.3) -- (15, 16.3);
  
  \draw [dashed] (30, -2.5) -- (30, 20.5);
  \draw [dashed] (-6, 20.5) -- (30, 20.5);
\end{axis}
\end{tikzpicture}
\caption[Konkav nytte af formue.]{Konkav nytte af formue. Her kunne $G$ opfattes som et tab eller en gevinst af et givet aktiv.}
\label{fig:Nyt}
\end{figure}

Som redegjort ovenfor, er både *ARA* samt *RRA* essientielle mål til kvantificering af risikopræferencer og dermed til at opnå forståelse for nyttefunktionen hos den enkelte investor. Konstateringer udledt fra den langsigtede økonomiske adfærd fastslår, at *RRA* ikke kan afhænge alene af formue. Dette kommer sig af, at formue og per capita forbrug er steget henover de seneste to århundreder. Det absolutte forhold mellem finansielle risici er ligeledes forøget -- siden disse risici er multiplikative -- mens de relative risici har været konstante. Samtidigt er der ikke fundet evidensbaseret på afkast og renter, der har påvist en langsigtet tendens, som respons til denne vækst. Altså vil investorer betale de samme relative omkostninger for at undgå en given finansiel risiko, uanset om de er velhavende eller ej, [@CampVic2003]. Dette foranlediger en til at tænke tanken, at *RRA* er uafhængig af formue og bør være konstant, [@Chiappori2008].

## Typer af nyttefunktioner{#typnyt}

Antagelser omhandlende: formen af nyttefunktioner og fordelingen af afkast, er påkrævet, for at kunne skabe en traktabel model. Flere nyttefunktioner har vist sig relevante inden for middelværdi-varians analyse, [@CampVic2003]. Nogle af disse er eksponentiel nytte, potens nytte samt kvadratisk nytte. Fælles for disse er, at de definerer nytte over formue. Udover disse findes andre mere eksotiske nyttefunktioner såsom Epstein-Zin nytte. I denne sektion undersøges ovenstående nærmere, og ud fra et kvantitativt aspekt vælges nyttefunktionen, som denne afhandling vil arbejde videre med.

Generelt vil en investors nytte -- defineret over formue -- afhænge af samtlige momenter relateret til formue. For at se dette laves en Taylor udvidelse af $U(W_{t+1})$ omkring den forventede formue, $\mathbb{E}(W_{t+1})$
\begin{align*}
U\left(W_{t+1}\right)=&U\left(\mathbb{E}\left[W_{t+1}\right]\right)+U'\left(\mathbb{E}\left[W_{t+1}\right]\right)+\frac{1}{2}U''\left(\mathbb{E}\left[W_{t+1}\right]\right)\left(W_{t+1}-\mathbb{E}\left[W_{t+1}\right]\right)^2\\
&+\sum_{n=3}^\infty \frac{1}{n!}U^{\left(n\right)}\left(\mathbb{E}\left[W_{t+1}\right]\right)\left(W_{t+1}-\mathbb{E}\left[W_{t+1}\right]\right),
\end{align*}

hvor $U^{(n)}$ er den $n$'te afledte af $U(\cdot)$. Tages nu den forventede værdi fås
\begin{align*}
\mathbb{E}\left[U\left(W_{t+1}\right]\right)=&U\left(\mathbb{E}\left[W_{t+1}\right]\right)+\frac{1}{2}U''\left(\mathbb{E}\left[W_{t+1}\right]\right)\mathbb{V}\left(W_{t+1}\right)\\
&+\sum_{n=3}^\infty \frac{1}{n!} U^{\left(n\right)}\left(\mathbb{E}\left[W_{t+1}\right]\right)\mathbb{E}\left[\left(W_{t+1}-\mathbb{E}\left[W_{t+1}\right]\right)^n\right],
\end{align*}

hvor $\mathbb{E}\left[(W_{t+1}-\mathbb{E}(W_{t+1}))^n\right]$ er det centrale moment af $n$'te orden. Fælles for disse momenter er, at de kvantificerer en investors villighed til at afgive eller optage diverse risici. Givetvis vil en grådig investor foretrække højere forventet formue end lavere, for faste centrale momenter af anden orden eller højere. En risikoavers investor, altså $U''(W)<0$, vil foretrække lavere varians af formue fremfor højere, for fast forventet formue samt for faste centrale momenter af tredje orden eller højere. Problemet opstår, når de centrale momenter højere end eller lig tredje orden ikke er ens for alle alternativer. I så fald ville man ikke kunne evaluere dem på baggrund af middelværdi og varians.

### Kvadratisk nytte

Kvadratisk nytte definerer nyttefunktionen som kvadratisk over formue. Den er fuldstændig defineret af dets første og anden afledte mht. formue. Alle dets højere momenter bliver nul, og skaber dermed ikke problemer i et middelværdi-varians setup, som argumenteret for ovenfor. For parametrene $a,b\in\mathbb{R}$ er kvadratisk nytte defineret som
\begin{equation}
U(W_{t+1})=aW_{t+1}-bW_{t+1}^2. (\#eq:Kvadnytte)
\end{equation}

Til forskel for nedenstående nyttefunktioner kræver kvadratisk nytte ikke fordelingsmæssige antagelser vedr. afkast af aktiverne. 

Under kvadratisk nytte vil maksimering af forventet nytte, som i Maksimeringsproblemet \@ref(eq:Nyttemaks), være ækvivalent til at maksimere en lineær kombination af middelværdi og varians, som i Maksimeringsproblemet \@ref(eq:Statmaks). Middelværdien af Ligning \@ref(eq:Kvadnytte) giver den forventede nytte
$$\mathbb{E}[U(W_{t+1})]=\mathbb{E}[W_{t+1}]-b(\mathbb{V}[W_{t+1}]+\mathbb{E}[W_{t+1}]^2),$$

og er dermed en funktion afhængende af både forventet formue og variansen af formue [@Munk2017]. Herudover vil *ARA* samt *RRA* begge være stigende i formue under kvadratisk nytte. Som argumenteret ovenfor vil stigende *ARA* være uhensigtmæssig. 

### Eksponentiel nytte
Eksponentiel nytte antager at variablene i modellen er normalfordelte. Lad $\theta\in\mathbb{R}$ være parameteren i modellen, da vil eksponentiel nytte være defineret ved
\begin{equation}
U(W_{t+1})=-\exp\left(-\theta W_{t+1}\right). (\#eq:Ekspnytte)
\end{equation}

Eksponentiel nytte antager, at *ARA* er konstant lig $\theta$, mens *RRA* kan stige med formue. Dette aspekt gør også eksponentiel nytte foretrukket ift. kvadratisk nytte. Eksponentiel nytte er også kendt under navnet *Constant Absolute Risk Aversion*. For en eksplicit opskrivning af forventningen af Ligning \@ref(eq:Ekspnytte) bemærkes følgende
$$W_{t+1}\sim \mathcal{N}\left(\mu_p,\sigma_p^2\right)$$

altså er terminalnytten normalfordelt for enhver mulig portefølje, $p$, givet at afkastene er normalfordelt. Regnes derfor på forventningen, fås
$$\mathbb{E}[U(W_{t+1})]=-\exp\left(-\theta\mu_p+\frac{\theta^2}{2}\sigma_p^2\right).$$

### Potens nytte
Potens nytte kræver, at afkast af aktiverne og formue er lognormal fordelt. *ARA* er faldende i formue og *RRA* antages til at være en konstant $\gamma\in\mathbb{R}$, [@CampVic2003]. Potens nytte er mere kendt under navnet *Constant Relative Risk Aversion*. Nyttefunktionen er defineret for $W_{t+1}\geq 0$, som
\begin{align}
U(W_{t+1})=\begin{cases} \frac{W_{t+1}^{1-\gamma}-1}{1-\gamma},\quad &\gamma\neq 1\\
\log(W_{t+1}),\quad &\gamma = 1. \end{cases} (\#eq:Potnytte)
\end{align}

For $\gamma\neq 1$ fås den forventede nytte til
$$\log(\mathbb{E}[W_{t+1})]=\mathbb{E}\left[\log(W_{t+1})\right]+\frac{1}{2}\mathbb{V}\left[\log(W_{t+1})\right],$$

hvor det bærende resultat vedr. middelværdien af en lognormalfordelt stokastisk variabel, se evt. Appendiks \@ref(underligteo), er anvendt. Logaritmefunktionen er en konkav funktion, dette betyder, at middelværdien af log af en stokastisk variabel er mindre end log af middelværdien, og forskellen er stigende i variabiliteten af den stokastiske variabel. For $\gamma \rightarrow 1$ haves
$$\mathbb{E}\left[U(W_{t+1})\right]=\mathbb{E}\left[\log(W_{t+1})\right].$$

### Sammenligning af nyttefunktioner
Som pointeret flere gange i ovenstående, burde *ARA* være faldende, eller under alle omstændigheder, ikke stige med formue. Dermed kan vi se bort fra kvadratisk nytte. Samtidigt vil det gøre potens nytte mere favorabel end eksponentiel nytte. Derudover er det konstante aspekt af *RRA* attraktivt under potens nytte, i og med, at det er nødvendigt ift. inferensen vedr. stabiliteten af finansielle variable under sekulær økonomisk vækst, [@CampVic2003].

Derudover vil valget mellem potens nytte og eksponentiel nytte også skabe de ovennævnte forskellige fordelingsmæssige antagelser. Eksponentiel nytte resulterer i simple afkast, hvis afkastene af aktiverne er normalfordelte, hvorimod potens nytte resulterer i simple afkast, hvis afkastene af aktiverne er lognormalfordelte.

Antagelsen om normalfordelte afkast er tiltalende, men begrænser sig til et kortsigtet perspektiv, i det, at antagelsen ikke kan holde mere end én periode. F.eks. kan vi antage, at kvartalvise afkast er normalfordelte, men så vil afkastet over to kvartaler ikke være normalfordelt. Dette kommer sig af, at de er produktet af to succesive normalfordelte afkast, og kun summen af normalfordelte variable er selv normalfordelt, ikke produktet. En antagelse om lognormalfordelte afkast vil modsat holde i en hver tidshorisont, siden produktet af to lognormale stokastiske variable selv er lognormal. Derudover vil en lognormal stokastisk variabel aldrig blive negativ, og dette er konsistent med de fleste finansielle aktivers begrænsede gældsforpligtelser.

Lognormale afkast vil til gengæld ikke nemt kunne flyttes fra aktivniveau til porteføljeniveau. Dette kommer sig af, at en portefølje givetvis er en lineær kombination af individuelle aktiver. Hvis disse individuelle aktiver antages at have lognormale afkast, vil porteføljeafkastet være et vægtet gennemsnit af lognormale afkast, men et sådant gennemsnit er ikke selv lognormalt. Dette problem overkommes imidlertidigt ved at arbejde med korte intervaller. Ikke-lognormaliteten af porteføljeafkastet formindskes ved at benytte kortere og kortere intervaller. I kontinuert tid vil problemet forsvinde i grænsen, [@CampVic2003].

## Fordeling af afkast {#fordafafk}

Brugen af afkast fremfor priser på aktiver, kommer sig af markedsinvariansen af afkast. Priser siges derimod at være kontrære, eller modsat rettede, [@Jondeau2007]. I bund og grund er priser *unit root* processer, dvs. stød til tidsserien af priser har permant effekt, dette kaldes undertiden også for ikke-stationære processer. *Unit root* processer siges også at have integration af første orden, $I(1)$. Afkast er derimod stationære processer, de har integration af nulte orden, $I(0)$, [@Verbeek2017]. For en ikke-stationær tidsserie vil momenterne ændre sig over tid, f.eks. vil middelværdien og variansen af en prisprocess på tidspunkt $t$, afhænge af den foregående periodes pris, altså på tidspunkt $t-1$. Den manglende markedsinvarians af prisprocesser holder dem ude af ligningen, da de grundet ovenstående ikke vil kunne producere *i.i.d.* stokatiske variable.

I det følgende vil vi adskille simple afkast og log^[Gennem resten af denne afhandling vil log referer til den naturlige logaritme.] afkast gennem notation. Det simple afkast noteres som $R_{t+1}$, som følger den gængse notation i litteraturen. Vi lader det simple brutto afkast være defineret som
$$R_{t+1}\equiv\frac{P_{t+1}}{P_t},$$

hvor $P_t\in\mathbb{R}_+$ er prisen på et aktiv, på tidspunkt $t$, og dermed $R_t\in\mathbb{R}$. Det simple afkast $R_t-1$ er den procentvise ændring over den respektive tidsperiode. Empiriske resultater har påvist, at simple afkast af aktiver udviser assymmetri og resulterer i højreskæve fordelinger bl.a. pga. de bagvedliggende virksomheder og/eller institutioneres begrænsede gældsforpligtelser. Derudover kan højreskævheden af simple afkast fremkomme på lang sigt grundet, at de er produktet af afkast over én-periode, som argumenteret for ovenfor.

I et forsøg på at overkomme disse faldgruber af simple afkast, benyttes log afkastet. Log afkastet noteres som $r_{t+1}$, og defineres som
$$r_{t+1}\equiv\log(1+R_{t+1}),$$

hvilket er en geometrisk og kontinuert følge, som dermed overholder markedsinvariansen.

## Opsummering {#opsunteo}

Dette kapitel præsenterede den grundliggende teori til porteføljeproblemet. 

# Afkastrelationer {#afkrel}
I Kapitel \@ref(unteo), blev den grundliggende teori bag porteføljevalget beskrevet. Som beskrevet kræver de underliggende modeller, at afkast er lognormalfordelte, og af den grund må afkastserierne transformeres. Mere specifikt blev investoren med potens nytte bl.a. beskrevet, her var det et krav, at de anvendte variable var logbaseret. Dette er specielt anvendeligt, når investorens porteføljevalg skal modelleres på lang sigt. Afkastprædiktabilitet lægger som navnet, op til at afkast *er* prædiktable. En forkastelse af *i.i.d.* antagelsen vil implicit medføre afkastprædiktabilitet. Dette kapitel vil fungere som en teoretisk gennemgang af udledningen af de specifikke aktivklasser som investoren står overfor, når porteføljevalget skal tages. For at udlede approksimative analytiske løsninger på tværs aktivklasser, vil den såkaldte loglineære relation af afkast blive anvendt, [@Campbell1988]. [@Campbell1988] viste i tilfældet af aktieafkast, hvordan en approksimativ loglineær relation af aktieafkast kunne etableres. På baggrund af denne relation har nyere litteratur anvendt deres metode på andre klasser af aktiver. At kunne etablere approksimative analytiske løsninger for alle aktivklasser er et afgørende element for at kunne skabe en robust VAR(1)-model i Kapitel \@ref(underligmodel). Sektion \@ref(opsafkrel) vil opsummere kapitlets fund.

## Afkasts- og nutidsværdi-relationer {#afkognut}

### Definition af aktieafkast {#defaktafk}
Denne Sektion har til formål at definere aktie afkast, dets log repræsentation samt dets relation til udbytte. Udledningen af én-periode brutto aktie afkastet baseres på [@Campbell1988]. Først betragtes brutto aktie afkastet fra tidspunkt $t$ til $t+1$, og dernæst udledes dets én-periode log afkast via en første ordens Taylor approksimation. Lad $R_{t+1}$ noterer én-periode brutto aktie afkastet, og lad det være defineret som
\begin{equation}
1+R_{t+1}=\frac{P_{t+1}+D_{t+1}}{P_t}, (\#eq:csaa)
\end{equation}

her er $P_t$ prisen af aktien på tidspunkt $t$. $D_t$ er udbytte på tidspunkt $t$. Tages nu log på begge sider af Ligning \@ref(eq:csaa) kan følgende udledes
\begin{equation}
r_{t+1}\approx p_{t+1}+\log\left(1+\exp\left(d_{t+1}-p_{t+1}\right)\right)-p_t. (\#eq:csaa2)
\end{equation}

Det observeres, at det andet led på højre side af Ligning \@ref(eq:csaa2) ikke er lineært. Dette løses ved at lave en førsteordens Taylor approksimation omkring middelværdien, $\overline{d_{t+1}-p_{t+1}}$^[Fordelene ved en sådan linearisering er, at det tillader en lineær statistisk analyse af aktieprisens bevægelser, som simplificerer det økonometriske arbejde. Derudover er der den generelle konsensus, at aktie afkast og udbytte følger en loglineær stokastisk process, og derfor er det nødvendigt at udarbejde en model, som er tilpasset denne antagelse.], dermed kan det andet led skrives som
\begin{equation}
f\left(\log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right)\right) = (1-\rho)(d_{t+1}-p_{t+1}) + c, (\#eq:csaa3)
\end{equation}

hvor $\rho$ og $c$ er såkaldte lineariseringsparametere, defineret som
\begin{align*}
\rho&=1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\\
c&=\log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right)-(1-\rho)(\overline{d_{t+1}-p_{t+1}}).
\end{align*}

Indsættes Ligning \@ref(eq:csaa3) nu i Ligning \@ref(eq:csaa2), kan det approksimative én-periode brutto aktie log afkast udledes til
\begin{equation}
r_{t+1}\approx \rho p_{t+1} + (1-\rho)d_{t+1}-p_t+c. (\#eq:csaa4)
\end{equation}

Ligning \@ref(eq:csaa4) betegnes undertiden som *Campbell-Shiller Loglinear Relation*, og antyder, at brutto aktie logafkastet approksimativt er et vægtet gennemsnit af fremtidige logpriser og logudbytte fratrukket fra den nuværende logpris med den tilhørende lineariseringsparameter $c$. Altså haves en approksimativ løsning for Ligning \@ref(eq:csaa). Eksempelvis var det gennemsnitlige *Dividend-Price Ratio* i U.S.A. mellem 1926 og 1994 var omkring $4\%$, dette ville betyde, at $\rho\approx 0.96$ i årlig data og $\rho\approx 0.997$ i månedlige data, [@Campbell1997]. Dette medfører en signifikant indvirkning fra proportionelle ændringer i aktiepriser på afkast ift. indvirkningen fra udbytte. 

Ligning \@ref(eq:csaa4) kan omskrives ift. *Dividend-Price Ratio*. Dette gøres ved at multiplicere med $-1$ og tillægge $d_t$ på begge sider af lighedstegnet
\begin{equation}
d_t-p_t=\rho(d_{t+1}-p_{t+1}) + r_{t+1} -\Delta d_{t+1}-c. (\#eq:csaa5)
\end{equation}

Tages nu forventningen af Ligning \@ref(eq:csaa5) på tidspunkt $t$ og ved samtidig overholdelse af transversalitetsbetingelsen
$$\lim_{n\to\infty } \rho^n\mathbb{E}_t\left[d_{t+n}-p_{t+n}\right]= 0,$$

kan der ved brug af rekursion, opnås den såkaldte *Dynamic Gordon Growth Model*
\begin{equation}
d_t-p_t=\sum_{j=0}^\infty \rho^j \mathbb{E}_t\left[r_{t+j+1}-\Delta d_{t+j+1}\right]-\frac{c}{1-\rho}. (\#eq:csaa6)
\end{equation}

Transversalitetsbetingelsen udeholder *bobler* i *Dynamic Gordon Growth Model*. Det følger igennem Ligning \@ref(eq:csaa6), at ændringer i log *Dividend-Price Ratio* må være grundet ændringer i: fremtidige afkast eller en ændring i forventningen til fremtidige udbyttebetalinger eller en kombination af begge. Et vigtigt aspekt af ovenstående relation er, at den er udledt på baggrund af definitionen af afkast og ikke en økonomisk model. Derudover viser Ligning \@ref(eq:csaa6) baggrunden for at medtage log *Dividend-Price Ratio*, som en forklarende variabel til responsvariablen aktieafkast: der må være en mellemliggende relation mellem bevægelser i aktieafkast eller vækst i udbyttebetalinger og ændringer i *Dividend-Price Ratio*. Ligning \@ref(eq:csaa6) hævder, at log *Dividend-Price Ratio* må bære på alt markedsinformation vedr. fremtidige bevægelser i aktieafkast eller udbytter.

### Definition af obligationsafkast {#defafobl}
Som en analog til det udledte resultat mellem aktieafkast og *Dividend-Price Ratio* fra Sektion \@ref(defaktafk), eksisterer der en relation mellem obligationsafkast og rentespændet. Dvs. at rentespændet spiller en sammenlignelig rolle for *Fixed Income* markederne, som *Dividend-Price Ratio* gjorde det for aktiemarkederne [@Campbell1997]. Først etableres egenskaberne for nulkupon obligationer, for herefter at udarbejde relationen for kupon obligationer. 

Rentespændets prædiktabilitet af obligationsafkast kan blive udledt, ved at betragte et marked bestående kun af nulkupon obligationer. Den nominelle pris på tidspunkt $t$, for en nulkupon obligation med løbetid $n$, noteres som $P_t^n$. Den tilhørende effektive rente betegnes $Y_t^n$. Ved tilbagediskontering af det fremtidige cashflow kan prisen i dag findes til
\begin{equation}
P_t^n=\frac{1}{(1+Y_t^n)^n}. (\#eq:csba1)
\end{equation}

Tages nu log på Ligning \@ref(eq:csba1) for herefter at isolere log af den effektive rente, kan følgende opnås
\begin{equation}
y_t^n=-\frac{1}{n}p_t^n. (\#eq:csba2)
\end{equation}

Ved brug af Ligning \@ref(eq:csba1), ses at én-periode brutto afkastet på obligationen fra tidspunkt $t$ til $t+1$ bliver
\begin{equation}
1+R_{t+1}^n=\frac{P_{t+1}^{n-1}}{P_t^n}=\frac{(1+Y_t^n)^n}{(1+Y_t^{n-1})^{n-1}}. (\#eq:csba3)
\end{equation}

Ligning \@ref(eq:csba3) viser at $n$-periode afkastet bliver $n-1$-periode afkastet på tidspunkt $t+1$. Dette kan lade sige gøre idet, at $n$-periode obligationen er holdt til horisonten $n$. Ved at gå fra $t$ til $t+1$ er den første periode af $n$-periode obligationen nu afsluttet, dermed bliver $n$-periode obligationen nu $n-1$-periode obligationen på tidspunkt $t+1$. Ved at tage log på Ligning \@ref(eq:csba3), bliver én-periode brutto afkastet for beholdningsperioden $n$ lig
\begin{equation}
r_{t+1}^n=n y_t^n - (n-1) y_{t+1}^{n-1}. (\#eq:csba4)
\end{equation}

Fra Ligning \@ref(eq:csba4) observeres det, at afkastet er et vægtet gennemsnit af den nuværende effektive rente og den fremtidige effektive rente på obligationen med løbetid $n$. Ved isolation af den nuværende effektive rente opnås
\begin{equation}
y_t^n = \frac{1}{n} \left(r_{t+1}^n + (n-1) y_{t+1}^{n-1}\right). (\#eq:csba5)
\end{equation}

Kombineres udtrykket for den effektive rente $y_t^n$ samt implikationen for $p_t^n$, kan Ligning \@ref(eq:csba4) løses ved rekursion, og dermed opnå
\begin{equation}
y_t^n = \frac{1}{n} \sum_{i=0}^{n-1} r_{t+1+i}^{n-1}. (\#eq:csba6)
\end{equation}

Ligning \@ref(eq:csba6) viser, at den effektive rente er lig det gennemsnitlige afkast pr. periode, givet at obligationen er holdt til udløb, $n$. Derudover kan Ligning \@ref(eq:csba6) omskrives i termer af rentespændet, eftersom
\begin{equation}
s_t^n\equiv y_t^n - y_t^1. (\#eq:csba7)
\end{equation}

Rentespændet findes nu ved at tage den betingede forventning til den fremtidige (korte) rente og ændringer i risikopræmien
\begin{equation}
s_t^n=\frac{1}{n} \sum_{i=1}^{n-1} \mathbb{E}_t\left[(n-1)\Delta y_{t+1}^1\right] + \frac{1}{n}\sum_{i=0}^{n-1}\mathbb{E}_t\left[(r_{t+1+i}^{n-i}-y_t^1)\right]. (\#eq:csba8)
\end{equation}

Ved denne opskrivning ses, at ændringer i rentespændet er grundet bevægelser i den fremtidige (korte) rente og/eller ændringer i den fremtidige risikopræmie. Resultatet er dermed en analog til relationen mellem aktieafkast og *Dividend-Price Ratio* i *Dynamic Gordon Growth Model*. [@Fama1987] viser, at rentespændet implicit har styrke til at prædiktere obligationsafkast, hvis obligationsafkastet er tidsvarierende.

Nu fortsættes udledningen for relationen ift. kupon betalende obligationer. Generelt set kan en kupon obligation betragtes som en række nulkupon obligationer. Hvor hver nulkupon obligation har en pålydende værdi lig kuponbetalingen for hver pågældende kuponbetalingsdag, inkl. udløbsbetalingen, [@Campbell1997]. Udover løbetiden på obligationen, vil prisen også afhænge af kuponrenten. For at se dette betragtes en kupon obligation med kuponbetalinger lig $C$, med en periodisk effektiv rente på $Y_t^{c,n}$, som samtidig defineres som den periodiske diskonteringsfaktor. Dermed bliver prisen på obligationen
\begin{equation}
P_t^{c,n}=\frac{C}{(1+Y_t^{c,n})}+\frac{C}{(1+Y_t^{c,n})^2}+\cdots+\frac{C}{(1+Y_t^{c,n})^n}.  (\#eq:csba9)
\end{equation}

En analytisk løsning for Ligning \@ref(eq:csba9) ift. $Y_t^{c,n}$ er ikke mulig, ergo må ligningen derfor løses numerisk. Ved sammenligning med den effektive rente på en nulkupon obligation, vil den effektive rente på en kuponbetalende obligation ikke nødvendigvis være lig det periodiske afkast, hvis obligationen holdes til udløb. Lighed opstår kun når, at kuponbetalingerne er geninvesteret til en rente lig den effektive rente. Fra Ligning \@ref(eq:csba9) kan to specialtilfælde ligeledes udledes. Hvis $n$ er uendelig, er obligationen et uamortisabelt lån eller en såkaldt perpetuitet. Dette er ensbetydende med, at den effektive rente er lig forholdet mellem prisen på obligationen og kuponrenten. Derudover kaldes tilfældet, hvor $P_t^{c,n}=1$ at obligationen sælges til kurs pari.

Når kuponobligations afkastet defineres som
\begin{equation}
1+R_{t+1}^n = \frac{P_{t+1}^{n-1}+C}{P_t^n} (\#eq:csba10)
\end{equation}

kan kuponbetalingerne sammenlignes med udbyttebetalinger. Ligning \@ref(eq:csba10) er reelt set brutto afkastet for kuponobligationen, ved at holde den fra $t$ til $t+1$, med $n$ perioder til udløb. En tilsvarende loglineær approksimation eksisterer for afkastet af kuponobligationer, som det var tilfældet for aktieafkastet. Benyttes denne approksimation bliver én-periode afkastet, $r_{t+1}^{c,n}$, tilnærmelsesvis lig det følgende
\begin{equation}
r_{t+1}^{c,n}\approx k + \rho p_{t+1}^{c,n-1} + (1-\rho)c - p_t^{c,n} (\#eq:csba11)
\end{equation}

Fra Ligning \@ref(eq:csba11) og Ligning \@ref(eq:csaa4) ses, at udbytte og kuponbetalingenr spiller en sammenlignelig rolle, når afkast skal approksimeres for hhv. aktier og obligationer. Her er $k$ og $\rho$ lineariseringsparametere, som er givet ved 
\begin{align*}
k &= -\log(1-\rho)\log\left(\frac{1}{\rho-1}\right)\\
\rho&= \frac{1}{\exp\left(\overline{c-p}\right)}.
\end{align*}

Hvis kuponobligationen bliver solgt til kurs pari, vil $\rho$ reduceres til
$$\rho=\frac{1}{1+C}.$$

Ved rekursion indtil udløb af kuponobligationen kan der udledes en ligning, som kobler obligationsprisen til dens følge af kuponbetalinger og det fremtidige afkast på obligationen, altså vil prisen blive
\begin{equation}
p_t^{c,n}\approx\sum_{i=0}^{n-1} \rho^i \left(k+(1-\rho)c - r_{t+1+i}^{c,n-i}\right). (\#eq:csba12)
\end{equation}

En tilsvarende approksimation af den effektive log rente eksisterer ligeledes, rekursion for denne medfører
\begin{equation}
p_t^{c,n}\approx\sum_{i=0}^{n-1} \rho^i \left(k+(1-\rho)c - y_{t}^{c,n}\right). (\#eq:csba13)
\end{equation}

Kombineres Ligning \@ref(eq:csba12) med Ligning \@ref(eq:csba13), kan den følgende relation opnås
\begin{equation}
y_{t}^{c,n}\approx \frac{(1-\rho)}{(1-\rho^n)}\sum_{i=0}^{n-1} \rho^i r_{t+1+i}^{c,n-i}. (\#eq:csba14)
\end{equation}

Til forskel for nulkuponobligationen, hvor der eksisterer en eksakt relation mellem den effektive log rente og nulkupon obligations log afkastet, Ligning \@ref(eq:csba5), eksisterer der kun en approksimativ relation for kuponobligationen. En forskel, som adskiller nulkuponobligationer fra kuponobligationer er varighedens betydning. For nulkuponobligationer vil løbetiden direkte måle længden af tid en investor har investeret sin formue i obligationen. For kuponobligationer vil løbetiden være et uperfekt mål til at måle denne længde af tid, som investoren holder obligationen, eller portefølje af obligationer, da meget af værdiforøgelsen sker før udløb, [@Campbell1997]. For kuponobligationer vil *Macaulay* varighed være et bedre mål, [@Macaulay1938]. *Macaulay* varighed ser kuponobligationer som en række af nulkuponobligationer, og er et vægtet gennemsnit af løbetiderne på de indirekte nulkuponobligationer. Ved benyttelse af kuponobligationens effektive rente som diskonteringsfaktoren vil varigheden blive
\begin{equation}
D_t^{c,n}=\frac{C\sum_{i=1}^n \frac{i}{(1+Y_t^{c,n})} + \frac{n}{(1+Y_t^{c,n})^n}}{P_t^{c,n}}. (\#eq:csba15)
\end{equation}

Definitionen af *Macaulay* varighed
$$D^{c,n}=-\frac{\text{d} P_t^{c,n}}{\text{d} (1+Y_t^{c,n})}\frac{(1+Y_t^{c,n})}{P_t^{c,n}},$$

vil i stedet give anledning til følgende approksimation 
\begin{equation}
D^{c,n}\approx \frac{(1-\rho^n)}{(1-\rho)} = \frac{1-(1+Y_t^{c,n})^{-n}}{1-(1+Y_t^{c,n})^{-1}}, (\#eq:csba16)
\end{equation}

hvor ligheden følger, da obligationen antages at handle til kurs pari. Den endelige loglineære relation kan nu findes, ved at indsætte Ligning \@ref(eq:csba13) og Ligning \@ref(eq:csba16) i Ligning \@ref(eq:csba11).
\begin{equation}
r_{t+1}^{c,n}\approx D^{c,n} y_t^{c,n} - \left(D^{c,n} - 1\right) y_{t+1}^{c,n-1}=D^{c,n}(y_t^{c,n}- y_{t+1}^{n-1}) + y_{t+1}^{n-1}  (\#eq:csba17)
\end{equation}

Ligning \@ref(eq:csba17) kan ligeledes sammenlignes med Ligning \@ref(eq:csaa4), og blev først udledt af [@Campbell1983]. Men i dette tilfælde er ligningen et vægtet gennemsnit af varigheden på nuværende og fremtidige effektive renter. Ligning \@ref(eq:csba17) holder ligeledes for nulkuponobligationer, hvor varigheden erstatter løbetiden. Det andet lighedstegn viser ligeledes relationen til rentespændet, $y_t^{c,n}- y_{t+1}^{n-1}$. Som der givetvis må resultere i en forventning om positiv korrelation mellem afkastet og rentespændet i den empiriske sektion.

## Potentielle prædiktabilitetsvariable {#potpradik}
Denne sektion er en forlængelse af Sektion \@ref(afkognut), og fungerer som en undersøgelse og diskussion af variable med en potentiel prædiktionsevne. Med tiden er en lang række variable blevet foreslået til prædiktabilitet af afkast. Generelt kan disse variable grupperes i en række kategorier. I det følgende vil tre grupper bliver præsenteret: finasielle variable, rentestrukturs variable og makroøkonomiske variable. Denne inddeling er også anvendt i eksisterende litteratur, se bl.a. [@Koijen2011]. Den følgende undersøgelse af potentielle prædiktionsvariable vil bestå af kvalitative samt kvantitative analyser, som på den måde kommer til at foregå analysen relateret til porteføljevalget. Dette tillader at studere den potentielle lineære relation mellem merafkastet på aktiverne og variablene, og på den måde give en dybere inferens af de valgte foreklarende variable, som da vil blive benyttet i at modellere det optimale porteføljevalg.

### Finansielle variable
I Sektion \@ref(defaktafk) blev den fundamentale værdi af aktier benyttet til at argumentere for relation til *Dividend-Price Ratio*. Denne sektion benyttes til at diskutere andre potentielle finasielle variable, som før har vist statistisk styrke i at prædiktere aktie afkast. Samtidig er det muligt, at disse variable fanger variation, som allerede er forklaret igennem nogle af de eksistende variable. Derudover kan disse variable også muligvis forklare variation i afkastet på nogle af de andre aktiver ud over aktieafkastet. I det følgende vil *Price-Earnings Ratio*, *Book-to-Market Ratio*, aktievariansen, *Small Minus Big* og *High Minus Low* blive undersøgt.

[@Fama1988] finder, at både *Dividend-Price Ratio* samt *Price-Earnings Ratio* har statistisk styrke i at prædiktere forventede aktieafkast, og argumenterer for, at *Dividend-Price Ratio* er mindre variabel end *Price-Earnings Ratio* som indeholder en del støj. Derudover finder [@Lamont1998] evidens for, at den aggregerede *Dividend Payout Ratio* prædikterer merafkast på både aktier og obligationer. [@Lamont1998] argumenterer modsat [@Fama1988], at variansen fra *Price-Earnings Ratio* ikke er støj, men derimod information om forventede afkast. Givet disse ovenstående fund, vil en medtagelse af *Price-Earnings Ratio* være relevant for den følgende analyse.

*Book-to-Market Ratio* er ligeledes en finansiel variabel, som måler værdien af en aktie ved at sammenligne den bogførte værdi relativt til markedsværdien. *Book-to-Market Ratio* har i litteraturen vist at kunne forklare variationen i forventede aktieafkast, [@Kothari1997].

Aktievariansen, som den bliver præsenteret her, er målt via metoden etableret af [@Schwert1987], der tager højde for autokorrelation. En tidsserie af $N_t$ daglige afkast er nødvendig for at estimere den månedlige aktievarians på tidspunkt $t$. Den estimerede varians er da lig summen af de kvadrerede daglige afkast, for en given måned, sammenlagt med to gange summen af produktet af to tilstødende daglige afkast. På denne måde korrigeres der for autokorrelation. 
\begin{equation}
\sigma^2_t = \sum_{i=1}^{N_t} r_{i,t} + 2 \sum_{i=1}^{N_t-1} r_{i,t}r_{i+1,t} (\#eq:aktvar1)
\end{equation}

Fra Ligning \@ref(eq:aktvar1) ses, at den estimerede middelværdi af stikprøven ikke fratrækkes de daglige afkast. Dette gøres ikke eftersom, at det har vist sig at have meget lille effekt, [@Schwert1987]. Ideen med at medtage variansen er, at den gennemsnitlige varians indeholder informationen på variansen af hele markedet. 

*Small Minus Big* og *High Minus Low* er ydereligere to finansielle variable/faktorer. Disse stammer fra [@French1993; @Fama2015], og mere specifikt deres *Three Factor Model* samt *Five Factor Model*. Disse variable anses for at være hhv. størrelsfaktoren på markedet og værdifaktoren på markedet. Faktorerne er skabt via en dannelse af seks markedsporteføljer. [@French1993] finder, at begge faktorer er signifikante i at prædiktere merafkastet på markedsporteføljen. Ved tilføjelse af yderligere to faktorer -- profitabilitesfaktoren og investeringsfaktoren -- finder [@Fama2015], at *High Minus Low* bliver redundant i deres underliggende model. Eftersom tidsserien for *High Minus Low* er fuldstændig forklaret af de andre fire faktorer. De finder bl.a., at investeringsfaktoren har en meget negativ korrelation med *High Minus Low* på $-0.7$.

### Rentestrukturs variable
I denne sektion undersøges fem rentestruktursvariable, som tidligere er foreslået i litteraturen. Disse er *Yield Spread*, *Term Spread*, *Credit Spread*, *Default Spread* og den nominelle rente.

*Term Spread* defineres som forskellen mellem den effektive lange rente og den 90-dages *T-Bill*, og er på den måde rentespændet mellem to obligationsinstrumenter med forskellige løbetider. Igennem dette rentespænd kan hældningen på rentekurven ligeledes findes. Basalt set vil rentekurven blive stejlere des højere værdien af rentespændet bliver. [@Fama1989] viser at en del af præmien i forventede afkast af hhv. aktier og obligationer er prædikteret gennem rentestrukturen. Disse afkast har vist sig at have forskellige konjukturmønstre. Altså vil det forventede afkast over aktier og obligationer bevæge sig kontracyklisk med de generelle konjukturer i økonomien. For at have en bredere del af rentekurven med, medtages ligeledes *Yield Spread*. Denne variabel viser rentespændet på kort sigt, eftersom det er forskellen mellem den effektive korte rente og den 90-dages *T-Bill*.

*Credit Spread* defineres som forskellen mellem lavt ratede virksomhedsobligationernes effektive rente og den 90-dages *T-Bill* rente. Dette følger metoden af [@Keim1986]. Kreditspændet er en ex ante variabel, som følger niveauet for lavt ratede obligationers priser. [@Keim1986] beviser, at variablen summerer ex ante information vedr. forventede risikopræmier. På samme vis defineres *Default Spread* som forskellen mellem lavt ratede virksomhedsobligationers effektive rente og højt ratede virksomhedsobligationerns effektive rente. [@Fama1989] finder bl.a. at *Default Spread* fanger variation i forventede obligations- og aktieafkast. Derudover beskriver de, at de største bevægelser i denne variabel og i afkastene som variablen prædikterer er relateret til langstrækte økonomiske hændelser, som spænder over flere økonomiske konjukturer.

Den nominelle (korte) rente har før vist at have statistisk styrke til at prædiktere afkast, [@Campbell2005]. Ved at inkludere både den nominelle rente (brutto) og realrenten (netto), fanges inflation i modellen, [@Campbell2005].

### Makroøkonomiske variable
Udover de finansielle variable og rentestruktursvariablene medtages én makroøkonomisk variabel. Denne variabel er *Federal Funds Rate*. En generel egenskab af makroøkonomiske variable er, at de ikke baserer sig på markedspriser. [@Cochrane2008] finder, at priserne som prædikterer afkast er korreleret med økonomiske konjukturcyklusser, med højere forventet afkast under lavkonjukturer.

En relevant makroøkonomisk del til at forklare variationen i specielt obligationsafkast er finanspolitikken. [@Dai2005] undersøger specielt finanspolitikkens indflydelse ved at inkorporere *Federal Funds Rate* som en forklarende variabel. De finder, at denne -- inkl. flere andre variable -- har statistisk styrke til at prædiktere obligationsafkast. 

## Opsummering {#opsafkrel}
Dette kapitel fungerede som et overblik over de approksimative og eksakte analytiske resultater på tværs af en række af aktiver. Ved benyttelse af den loglineære afkast approksimation af [@Campbell1988], blev aktivklassernes nutidsværdi relateret til forventede fremtidige betalinger. Dette tillod at prædiktive relationer på tværs af aktivklasserne blev dannet, som er essentielle, når den mulige prædiktabilitet skal begrundes. Disse relationer vil derfor også kunne inkorporeres i den følgende VAR(1)-model. Derudover er en lang række variable ligeledes blevet præsenteret og diskuteret. Disse potentielle prædiktionsvariable er medtaget grundet tidligere fund i litteraturen, som viser at prædiktabiliteten af afkast kan fanges af flere variable end de variable, som har en fundamental relation til afkast.

# Vector Autoregressive Model {#varkapitel}

I dette kapitel præsenteres det dynamiske system, som har til formål at modellere afkastet og prædiktionsvariablene, til den empiriske analyse. Dette gøres hovedsageligt ud fra teorien bag [@Userguide2004] med enkelte dele, som varierer. At kunne modellere afkast -- og på den måde implicit antage  tidsvarierende afkast -- er den fundamentale egenskab, som gør at Markowitz' portefølje teori fra Kapitel \@ref(unteo) kan udvides. Sektion \@ref(setafinv) definerer og etablerer den multivariate VAR(1)-model. Her udledes betingede momenter for responsvariablene og derudover udledes de betingede momenter af afkast. Sektion \@ref(biasadjvar) viser, hvordan bias-justering i VAR(1) koefficientestimaterne kan foretages, ved brug af metoden fra [@Engsted2012] og [@Pope1990]. 

## Sættet af investeringsmuligheder {#setafinv}
Først etableres en model, som kan modellere forventet afkast og risiko af aktier på tværs af investeringshorisonter.

\subsection{Afkastdynamikken}

Lad $\bm{z}_{t+1}$ være en $m\times 1$ vektor, hvis indgange er afkastet på alle aktiver som vi vil undersøge samt værdierne af tilstandsvariablene på tidspunkt $t+1$. Denne vektor opskrives som
    \begin{equation}
        \bm{z}_{t+1}\equiv
        \begin{bmatrix}
        r_{0,t+1}\\
        \bm{r}_{t+1}-r_{0,t+1}\bm{\ell}\\
        \bm{s}_{t+1}
        \end{bmatrix}\equiv
        \begin{bmatrix}
        r_{0,t+1}\\
        \bm{x}_{t+1}\\
        \bm{s}_{t+1}
        \end{bmatrix},
    \end{equation}
hvor $r_{0,t+1}$ er netto log-afkastet af det aktiv, som vores merafkast for de andre aktiver regnes ud fra, $\bm{x}_{t+1}$ er en vektor af log merafkast for alle andre aktiver, og $\bm{s}_{t+1}$ er en vektor indeholdende realisationerne af tilstandsvariablene. Vi antager samtidig, at der eksisterer $n+1$ klasser af aktiver og $m-n-1$ tilstandsvariable.

\vspace{5mm}

Nu vises, hvordan momenterne af afkastene fremkommer ved brug af en VAR process. Det antages, at aktivernes afkast samt tilstandsvariablene følger en $\text{VAR}(1)$ process
    \begin{equation}
        z_{i,t+1}=\varphi_0+\varphi_1 z_{1,t}+\dots+\varphi_i z_{i,t}+\dots+v_{i,t+1},
    \end{equation}
hvor hver variabel, $z_{i,t+1}$, afhænger lineært af en konstant, værdien af variablen på tidspunkt $t$, værdien af alle andre variable på tidspunkt $t$ samt et fejlled.

\vspace{5mm}

I matrixnotation fås da følgende kompakte opskrivning
    \begin{equation}\label{eq:1}
        \bm{z}_{t+1}=\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_t+\bm{v}_{t+1},
    \end{equation}
hvor $\bm{\Phi}$ er en vektor af afskæringer, $\bm{\Phi}_1$ er en kvadratisk matrix, som indeholder hældningskoefficienterne og $\bm{v}_{t+1}$ er en vektor fejlled til: realisationerne af afkast samt alle afkast variable i modellen, med middelværdi $0$.

\vspace{5mm}

For at få stationalitetsbetingelsen opfyldt i modellen, antages, at
    \begin{equation*}
        \det(\bm{\Phi}_1)\in(-1,1).
    \end{equation*}
Dvs. at determinanten matricen -- bestående af hældningskoefficienter -- er begrænset mellem $-1$ og $1$.

\vspace{5mm}

Slutteligt antages, at fejlleddet er normalfordelt
    \begin{equation}\label{eq:2}
        \bm{v}_{t+1}\overset{\text{i.i.d.}}{\sim}\mathcal{N}(0,\bm{\Sigma}_v),
    \end{equation}
hvor middelværdien er nul, som tidligere nævnt, og $\bm{\Sigma}_v$ er kovariansmatricen, som tillige er symmetrisk.

For notationens skyld sættes
    \begin{equation*}
        \bm{\Sigma}_v\equiv \mathbb{V}_t(\bm{v}_{t+1})=
        \begin{bmatrix}
        \bm{\sigma}_0^2 & \bm{\sigma}_{0x}' & \bm{\sigma}_{0s}'\\
        \bm{\sigma}_{0x} & \bm{\Sigma}_{xx} & \bm{\Sigma}_{xs}'\\
        \bm{\sigma}_{0s} & \bm{\Sigma}_{xs} & \bm{\Sigma}_{s}\\
        \end{bmatrix},
    \end{equation*}
hvor indgangene på diagonalen er: variansen af netto afkastet på vores benchmark aktiv, kovariansmatricen af uventede merafkast og kovariansmatricen af stød til tilstandsvariablene. Uden for diagonalen består indgangene af: kovariansen mellem netto afkastet af benchmark aktivet og hhv. merafkastet for alle andre aktiver samt stødene til tilstandsvariablene.

\vspace{5mm}

På trods af den simplificerende antagelse om tidsinvariant varians ikke virker empirisk sandsynlig, er antagelsen relativt uproblematisk givet, at fokus er på det langsigtede porteføljevalg hos investoren. [@Chacko2005] argumenterer for -- ved brug af en realistisk kalibreret model af aktieafkasts volatilitet -- at størrelsesordenen af volatiliteten af risiko ikke er stor nok til at have indvirkning på porteføljevalget for investorer med en lang investeringshorisont, relativt til porteføljevalg af investorer med en kort investeringshorisont. Herudover viser empiriske undersøgelser, at ændringer i risiko er kortvarige fænomener, [@Camp1987], men samtidig kan kovariansmatricen stadig ændre sig på tværs af investeringshorisonter.

\vspace{5mm}

Den ubetingede middelværdi og kovariansmatrix af $\bm{z}_{t+1}$ er givet ved
    \begin{align*}
        \mathbb{E}_t\left[\bm{z}_{t+1}\right] &= (\bm{I}_m-\bm{\Phi}_1)^{-1}\bm{\Phi}_0\\
        \text{vec}(\bm{\Sigma}_{zz}) &= (\bm{I}_{m^2}-\bm{\Phi}_1\otimes\bm{\Phi}_1)^{-1}\text{vec}(\bm{\Sigma}_v).
    \end{align*}
Ovenstående ligninger ligger også til grund for determinantbetingelsen: hvis ikke determinanten af $\bm{\Phi}_1$ var begrænset af $-1$ og $1$, ville den ubetingede middelværdi og varians af $\bm{z}_{t+1}$ ikke være defineret.

\subsection{Betingede momenter for $k$-perioder}
Nu udledes den betingede middelværdi og kovariansmatrix af $(\bm{z}_{t+1}+\dots+\bm{z}_{t+k})$ for enhver horisont $k$. Dette gøres eftersom det akkumulerede $k$-periode afkast fremkommer ved at tillægge én-periode log-afkast over $k$ perioder. Ved rekursion af Ligning \eqref{eq:1} fås
    \begin{align*}
        \bm{z}_{t+1}&=\bm{\Phi}_0+\bm{\Phi}_1 \bm{z}_t+\bm{v}_{t+1}\\
        \bm{z}_{t+2}&=\bm{\Phi}_0+\bm{\Phi}_1 \bm{z}_{t+1}+\bm{v}_{t+2}=\bm{\Phi}_0+\bm{\Phi}_1\bm{\Phi}_0+\bm{\Phi}_1\bm{\Phi}_1 \bm{z}_t +\bm{\Phi}_1 \bm{v}_{t+1}+\bm{v}_{t+2}\\
        &\vdots\\
        \bm{z}_{t+k}&=\bm{\Phi}_0+\bm{\Phi}_1\bm{\Phi}_0+\bm{\Phi}_1^2\bm{\Phi}_0+\dots+\bm{\Phi}_1^{k-1}\bm{\Phi}_0+\bm{\Phi}_1^k \bm{z}_t+\bm{\Phi}_1^{k-1}\bm{v}_{t+1}+\bm{\Phi}_1^{k-2}\bm{v}_{t+2}+\dots+\bm{\Phi}_1 \bm{v}_{t+k-1}+\bm{v}_{t+k}.
    \end{align*}
Herefter tillægges udtrykkene for $\bm{z}_{t+1}$, $\bm{z}_{t+2},\dots,\bm{z}_{t+k}$ og det følger at
    \begin{align*}
        \bm{z}_{t+1}+\dots+\bm{z}_{t+k}=&\left(k+(k-1)\bm{\Phi}_1+(k-2)\bm{\Phi}_1^2+\dots+\bm{\Phi}_1^{k-1}\right)\Phi_0\\
        &+\left(\bm{\Phi}_1^k+\bm{\Phi}_1^{k-1}+\dots+\bm{\Phi}_1\right)\bm{z}_t\\
        &+\left(1+\bm{\Phi}_1+\dots+\bm{\Phi}_1^{k-1}\right)\bm{v}_{t+1}\\
        &+\left(1+\bm{\Phi}_1+\dots+\bm{\Phi}_1^{k-2}\right)\bm{v}_{t+2}\\
        &+\dots\\
        &+(I+\bm{\Phi}_1)\bm{v}_{t+k-1}+\bm{v}_{t+k}.
    \end{align*}
Ved brug af sumoperatoren kan ovenstående skrives på kompakt form
    \begin{equation}
        \bm{z}_{t+1}+\dots+\bm{z}_{t+k}=\left(\sum_{i=0}^{k-1} (k-i)\bm{\Phi}_1^i\right)\bm{\Phi}_0+\left(\sum_{j=1}^k \bm{\Phi}_1^j\right)\bm{z}_t+\sum_{q=1}^k\left(\sum_{p=0}^{k-q} \bm{\Phi}_1^p \bm{v}_{t+q}\right).
    \end{equation}
Nu kan de betingede $k$-periode momenter af tilstandsvektoren beregnes. Den betingende middelværdi er
    \begin{equation}
        \mathbb{E}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}]=\left(\sum_{i=0}^{k-1}(k-1)\bm{\Phi}_1^i\right)\bm{\Phi}_0+\left(\sum_{j=1}^k \bm{\Phi}_i^j\right)\bm{z}_t,
    \end{equation}
hvor antagelsen i Ligning \eqref{eq:2} benyttes.

\vspace{5mm}

Den betingede varians er
    \begin{align}
        \mathbb{V}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}]
        &=\mathbb{V}_t\left[\left(\sum_{i=0}^{k-1}(k-1)\bm{\Phi}_1^i\right)\bm{\Phi}_0+\left(\sum_{j=1}^k \bm{\Phi}_i^j\right)\bm{z}_t +\sum_{q=1}^k\left(\sum_{p=0}^{k-q}\bm{\Phi}_1^p \bm{v}_{t+q}\right)\right] \nonumber\\
        &=\mathbb{V}_t\left[\sum_{q=1}^k\left(\sum_{p=0}^{k-q} \bm{\Phi}_1^p \bm{v}_{t+q}\right)\right] \label{eq:3},
    \end{align}
hvor de første to led i variansen forsvinder, da de er konstante eller kendte på tidspunkt $t$. Ved omskrivning af Ligning \eqref{eq:3} fås
    \begin{align*}
        \mathbb{V}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}]&=\mathbb{V}_t\big[\big(I+\bm{\Phi}_1+\dots+\bm{\Phi}_1^{k-1}\big)\bm{v}_{t+1}+\big(I+\bm{\Phi}_1+\dots+\bm{\Phi}_1^{k-2}\big)\bm{v}_{t+2}\\
        &\hphantom{=}+\dots+\big(I+\Phi_1\big)\bm{v}_{t+k-1}+\bm{v}_{t+k}\big]\\
        &=\Sigma_v+\big(I+\bm{\Phi}_1\big)\Sigma_v(I+\bm{\Phi}_1)'+\big(I+\bm{\Phi}_1+\bm{\Phi}_1\bm{\Phi}_1\big)\Sigma_v\big(I+\bm{\Phi}_1+\bm{\Phi}_1\bm{\Phi}_1\big)'\\
        &\hphantom{=}+\dots+\big(I+\bm{\Phi}_1+\dots+\bm{\Phi}_1^{k-1}\big)\Sigma_v\big(I+\bm{\Phi}_1'+\dots+\bm{\Phi}_1^{k-1}\big)',
    \end{align*}
som følger af omskrivning af leddene, og at den betingede kovariansmatrix af $v_{t+i}$ er den samme for alle $i$.

\subsection{Betingede momenter for $k$-periode afkast}
Eftersom interessen kun er i den del af VAR-processen, som indeholder afkast, benyttes de såkaldte selektionsmatricer.

Det forventede $k$-periode log-(mer)afkast pr. periode, kan udtrækkes via følgende
    \begin{equation*}
        \bm{H}_r=\begin{pmatrix}\bm{I}_{n+1} & \bm{0}_{m-n}\end{pmatrix},
    \end{equation*}
ved at anvende denne matrix på den betingede middelværdi fås da
    \begin{equation}
        \frac{1}{k}\begin{pmatrix}
        \mathbb{E}_t\left[ r_{0,t+1}^{(k)} \right]\\
        \mathbb{E}_t\left[ \bm{r}_{t+1}^{(k)}-r_{0,t+1}^{(k)}\bm{\bm{\ell}} \right]
        \end{pmatrix}=\frac{1}{k}\bm{H}_r\mathbb{E}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}].
    \end{equation}
Anvendes den på den betingede varians fås
    \begin{equation}
        \frac{1}{k}\mathbb{V}_t\begin{bmatrix}
        r_{0,t+1}^{(k)}\\
        \bm{r}_{t+1}^{(k)}-r_{0,t+1}^{(k)}\bm{\bm{\ell}}
        \end{bmatrix}=\frac{1}{k}\begin{pmatrix}
        \sigma_0^2(k) & \bm{\sigma}_{0x}(k)'\\
        \bm{\sigma}_{0x}(k) & \bm{\Sigma}_{xx}(k)
        \end{pmatrix}=\frac{1}{k}\bm{H}_r\mathbb{V}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}]\bm{H}_r'.
    \end{equation}
Den anden selektionsmatrix som benyttes kan udtrække $k$-periode log-afkastet pr. periode
    \begin{equation}
        \bm{M}_r=\begin{pmatrix}
        1 & \bm{0}_{1\times n} & \bm{0}_{1\times (m-n-1)}\\
        \bm{\bm{\ell}}_n & \bm{I}_n & \bm{0}_{m-n-1}
        \end{pmatrix}.\label{eq:sel}
    \end{equation}
Anvendes den på den betingede middelværdi fås
    \begin{equation}
        \frac{1}{k}\begin{pmatrix}
        \mathbb{E}_t\left[ r_{0,t+1}^{(k)} \right]\\
        \mathbb{E}_t\left[ \bm{r}_{t+1}^{(k)} \right]
        \end{pmatrix}=\frac{1}{k}\bm{M}_r\mathbb{E}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}].
    \end{equation}
Slutteligt anvendes den på den betingede varians
    \begin{equation}
        \frac{1}{k}\mathbb{V}_t\begin{bmatrix}
        r_{0,t+1}^{(k)}\\
        \bm{r}_{t+1}^{(k)}
        \end{bmatrix}=\frac{1}{k}\bm{\Sigma}_{rr}(k)=\frac{1}{k}\bm{M}_r\mathbb{V}_t[\bm{z}_{t+1}+\dots+\bm{z}_{t+k}]\bm{M}_r'.\label{eq:bv}
    \end{equation}
    
\subsection{Bytteforholdet for en VAR-investor}
En investor, som bruger VAR-processen til at forudsige afkast, vil opfatte afkast-risiko bytteforholdet anderledes end en investor, som benytter den traditionelle metode (estimerer forventede afkast ud fra deres historiske gennemsnit). Mere specifikt benytter VAR-investoren den betingede forventning af afkast fremfor den ubetingede, som den traditionelle investor bruger.

Herudover vil en VAR-investor måle risikoen for hvert aktiv -- på kort sigt -- ud fra dens varians relativt til hvert specifikke aktivs betingede forventning af afkast til forskel for den ubetingede forventning af afkast. En vigtig ting at notere sig, er at den betingede varians er forskellig fra den ubetingede varians. Dette kan lade sig gøre, selv når der arbejdes under antagelsen, at den betingede varians er konstant over tid. Denne antagelse er også den, som arbejdes videre med i analysen. Begrundelsen for, at de er forskellige kommer sig af, at VAR-investoren ved, at noget af den ubetingede volatilitet for hvert aktiv er forudsigelig tidsvariation i afkastet, der derfor ikke tæller som risiko.  

For det tredje vil VAR-investoren vide, at risikoen på lang sigt af hvert aktivs afkast vil være forskelligt fra hvert aktivs risiko på kort sigt. For den traditionelle investor med konstante forventede afkast (de historiske gennemsnit) vil variansen af hvert aktiv være proportional med den tid aktivet holdes i. Annualiserede varianser er uafhængige af tiden, som aktivet bliver holdt i, og derfor vil den traditionelle investor have et konstant tal, som sammenholder risikoen for alle perioder for aktivet. For VAR-investoren vil annualiserede varianser enten stige eller falde, når investeringsperioden øges. Et andet vigtig aspekt er, at annualiserede kovarianser også kan stige eller falde over investeringsperioden.
    
## Bias justeret VAR-model {#biasadjvar}
Ved brug af den analytiske middelværdirette estimator foreslået af [@Pope1990], viser [@Engsted2012] at justering for bias i estimatorerne af middelværdi, i det multivariate setup, kan producere forskellige parameter estimater i den givne VAR($1$)-model. Benyttelse af *Ordinary Least Squares* regressionsestimater kan resultere i bias pga. den begrænsede stikprøvestørrelse og af den årsag mislede inferensen gjort på baggrund af VAR($1$) estimaterne. Herudover kan variablene besidde autokorrelation, hvis de udviser vedvarende effekter pga. stød til tidsserien. Den analytiske bias af OLS estimatoren, $\bm{\Phi}_1$, er udledt på baggrund af en Taylor udvidelse af høj orden. Dermed lader vi den analytiske bias, $\bm{B}_T$, være givet ved
\begin{equation}
\bm{B}_T=-\frac{\bm{b}}{T}+ O\left(T^{-\frac{3}{2}}\right), \label{eq:bias}
\end{equation}

hvor $T$ er stikprøvestørrelsen og tælleren er lig
$$\bm{b}=\bm{\Sigma}_v\left(\left(\bm{I}-\bm{\Phi}_1'\right)^{-1}+\bm{\Phi}_1'\left(\bm{I}-\left(\bm{\Phi}_1'\right)^2\right)+\sum_{i=1}^m \lambda \left(\bm{I}-\lambda\bm{\Phi}_1'\right)^{-1}\right)\bm{\Sigma}_z^{-1}.$$

Her er $\bm{\Sigma}_v$ den betingede kovariansmatrix af $v_t$, $\lambda$ er vektoren af egenværdier af $\bm{\Phi}_1$, $\bm{I}$ er identitetsvektoren og $m$ er antallet af tilstandsvariable i $\bm{z}$. Bias'en i Ligning \@ref(eq:bias) falder med raten $T^{-\frac{3}{2}}$, som $T\rightarrow \infty$. Den analytiske formel af [@Pope1990] giver ikke bias justerede afskæringer, $\bm{\Phi}_0$, men som [@Engsted2012] pointerer vil dette problem automatisk blive løst af de bias justerede hældninger. Dette sker eftersom det aritmetiske gennemsnit af en stationær variabel, er et ikke-biased estimat af den ubetingede sande middelværdi, og samtidig estimerer OLS præcis middelværdien af variablene i VAR-modellen, ved at fjerne første observation. Altså vil en VAR-model med bias justerede hældninger medføre ikke-biased estimater af $\bm{\Phi}_0$, givet modelrestriktionen, at de ubetingede middelværdier af variablene -- udledt fra VAR koefficienterne -- er lig deres aritmetiske gennemsnit
 
[@Engsted2012] finder både kvantitative og kvalitative effekter ved brug af bias justerede koefficienter ift. de regulere OLS estimater. De viser bl.a. hvordan *hedging* komponentet af porteføljeallokeringen ændrer sig for et kontinuum af risikoaversioner, hvor specielt mellemliggende risikoaversions værdier ($\gamma=2$) er særligt påvirket af biasjusteringen.^[Se evt. Figur 1 i [@Engsted2012].] Her bliver det optimale portefølgevalg påvirket, eftersom bias justeringen afstedkommer reducerede positioner for obligationer og aktier, gennem det intertemporale *hedging demand*, mens positionen for kontanter forøges.

## Opsummering

# Porteføljeteori {#porteteori}
I dette kapitel udvides teorien fra Kapitel \@ref(unteo). Mere specifikt sammenkobles porteføljeteorien fra Sektion \@ref(myoinv) og nytteteorien fra Sektion \@ref(typnyt). Dette gøres på baggrund af *CRRA*-nytte, i tilfældet, hvor investoren kan rebalancere sin portefølje periodisk og i det restringerede tilfælde, hvor ingen rebalancering er tilladt. Herefter beskrives den analytiske løsning til det dynamiske porteføljeproblem foreslået af [@JurVic2011].

## Den dynamiske portefølje {#crraportef}
I det følgende vil porteføljevalget udledes under antagelsen, at investoren har potens nytte dvs. *CRRA*-nytte samt, at afkastene på alle aktivklasser er lognormale.

Først antages, at afkastet på investorens portefølje er lognormal, dette betyder at $W_{t+1}$ ligeledes er lognormal. Under antagelsen om potens nytte, kan vi omskrive Maksimeringsproblemet \@ref(eq:Nyttemaks) til
\begin{align}
&\max\mathbb{E}_t\left[\frac{W_{t+1}^{1-\gamma}-1}{1-\gamma}\right] (\#eq:CRRAmaks)\\
&\text{ubb.}\,\,W_{t+1}=(1+R_{p,t+1})W_t.\notag
\end{align}

Maksimering af ovenstående forventning er ækvivalent til at maksimere log af forventningen, eftersom log-funktionen er strengt voksende, se evt. Figur \@ref(fig:Nyt), som er tegnet på baggrund af log-funktionen. Derudover kan: $\tfrac{1}{1-\gamma}$ og $-1$ fjernes fra Maksimeringsproblemet, eftersom de er konstante og derfor ikke vil påvirke optimum. Givet at $W_{t+1}$ er lognormal, kan resultatet fra Appendiks \@ref(underligteo) anvendes og dermed fås
\begin{align}
&\max \log\left(\mathbb{E}_t\left[W_{t+1}^{1-\gamma}\right]\right)=(1-\gamma){E}_t\left[w_{t+1}\right]+\frac{1}{2}(1-\gamma)^2\sigma_{wt}^2 (\#eq:CRRAmakslog)\\
&\text{ubb.}\,\,w_{t+1}=r_{p,t+1} + w_t.\notag
\end{align}

hvor $\sigma_{wt}^2$ er den betingede varians af log formuen, $w_{t+1}$. Derudover er budgetbegrænsningen ligeledes omskrevet til log-form. Her er $r_{p,t+1}=\log(1+R_{p,t+1})$, dvs. logafkastet på porteføljen, også kendt som det kontinuert tilskrevne porteføljeafkast. Ved division af $(1-\gamma)$ og samtidig substitution af budgetbegrænsningen ind i objektfunktionen, opnås følgende ubetingede maksimeringsproblem.
\begin{equation}
\max\mathbb{E}_t\left[r_{p,t+1}\right] + \frac{1}{2}(1-\gamma)\sigma_{pt}^2, (\#eq:CRRAmakslog2)
\end{equation}

hvor $\sigma_{pt}^2$ er den betingede varians af det kontinuert tilskrevne porteføljeafkast. Dette benytter faktummet at $\mathbb{E}_t(w_t)=w_t$ er deterministisk og ikke påvirker optimum eller variansleddet. Her kan det bemærkes, at
\begin{equation}
\mathbb{E}\left[r_{p,t+1}\right]+\frac{1}{2}\sigma_{pt}^2=\log(\mathbb{E}\left[1+R_{p,t+1}\right]), (\#eq:portafkls)
\end{equation}

fordi porteføljeafkastet er antaget til at være lognormal. Altså kan Maksimeringsproblemet \@ref(eq:CRRAmakslog2) omskrives til
\begin{equation}
\max\mathbb{E}_t[1+R_{p,t+1}] - \frac{1}{2}\gamma\sigma_{pt}^2. (\#eq:CRRAmakslog3)
\end{equation}

Dermed opnås det familiære maksimeringsproblem fra middelværdi-varians analysen, Sektion \@ref(myoinv). Altså vil investoren maksimere bytteforholdet mellem den forventede middelværdi og variansen på porteføljen. Denne afvejning er igen lineær, og *RRA*-koefficienten, $\gamma$, spiller samme rolle som parameteren $k$ i middelværdi-varians analysen. Fra ovenstående ses også, at variansen på porteføljen bliver straffet af en faktor på $\tfrac{\text{RRA}}{2}$.

Risikoaversion kan også analyseres på baggrund af Maksimeringsproblemet \@ref(eq:CRRAmakslog2).

  - For $\gamma>1$, vil investoren søge en mere sikker portefølje ved at straffe variansen af portefølje afkastet. Her er den positive effekt af det forventede afkast mere end opvejet af den negative effekt af variansen.
 
  - For $\gamma<1$, vil investoren søge en mere risikobærende portefølje ved at søge variansen af portefølje afkastet. Her er den positive effekt af det forventede afkast mere end opvejet af den negative effekt af variansen. Dette kommer sig af, at en højere varians, for det samme forventede log afkast, vil medføre et højere forventet simpelt afkast, se evt. Ligning \@ref(eq:portafkls).
  
  - For $\gamma=1$, vil investoren have log nyttefunktionen, og vælger porteføljen med det højeste log afkast. Denne portefølje betegnes undertiden som *Growth-Optimal*, siden det kan udledes at denne portefølje har højeste forventede afkast på lang sigt under visse antagelser, [@Kelly1956]. 

For at kunne løse Maksimeringsproblemet \@ref(eq:CRRAmakslog3), må et nyttigt approksimationsresultat tages i brug. Som tidligere nævnt er porteføljeafkastet en lineær kombination af vægtede afkast på aktiver. Log afkastet på porteføljen er log af denne lineære kombination, men ikke lig den lineære kombination af aktivernes log afkast. For at repræsentere log porteføljeafkastet på baggrund af log aktivafkast, over korte tidsintervaller, kan den følgende Taylor approksimation af den ikke-lineære funktion benyttes
$$r_{p,t+1}-r_{0,t+1}\approx \alpha_t (r_{t+1}-r_{0,t+1})+\frac{1}{2}\alpha_t(1-\alpha_t)\sigma_t^2.$$

Her repræsenterer $r_{t+1}$ log afkastet på det ene risikobærende aktiv, og $r_{0,t+1}$ repræsenterer log afkastet på det risikofrie aktiv. Forskellen mellem log porteføljeafkastet og den lineære kombination af de individuelle logafkast er givet ved $\alpha_t(1-\alpha_t)\tfrac{1}{2}\sigma_t^2$. Forskellen vil forsvinde, hvis vægtningen i det risikobærende aktiv er nul, eller hvis vægtningen i det risikofrie aktiv er nul. Ovenstående approksimation er eksakt i grænsen, ved benyttelse af kontinuerte diffusions processer for priserne på aktiverne, og kan udledes ved brug af *Itô's Lemma*, [@CampVicCha2003]. Ovenstående approksimation kan nu benyttes, og dermed kan Maksimeringsproblemet \@ref(eq:CRRAmakslog2) skrives i form af merafkast på porteføljen.
\begin{equation}
\max\alpha_t(\mathbb{E}_t[r_{t+1}] - r_{0,t+1}) + \frac{1}{2}\alpha_t(1-\alpha_t)\sigma_t^2 + \frac{1}{2}(1-\gamma)\alpha_t^2\sigma_t^2, (\#eq:CRRAmakslog4) 
\end{equation}

med den tilhørende løsning
\begin{equation}
\alpha_t=\frac{\mathbb{E}_t[r_{t+1}] - r_{0,t+1}+\frac{1}{2}\sigma_t^2}{\gamma\sigma_t^2}.
\end{equation}

Som tilmed er ækvivalent til den optimale vægtning, Ligning \@ref(eq:Statmaks), fra middelværdi-varians analysen. I tilfældet, hvor investoren står overfor $n>1$ risikobærende aktiver, vil Taylor approksimationen af den ikke-lineære funktion være givet ved
\begin{equation}
r_{p,t+1}-r_{0,t+1}\approx \bm{\alpha}'_t (\bm{r}_{t+1}-r_{0,t+1}\bm{\ell})+\frac{1}{2}\bm{\alpha}'_t\bm{\sigma}_t^2 - \frac{1}{2} \bm{\alpha}_t'\bm{\Sigma}_t\bm{\alpha}_t. (\#eq:Multtaylor)
\end{equation}

Den optimale løsning vil være givet ved
\begin{equation}
\bm{\alpha}_t=\frac{1}{\gamma}\bm{\Sigma}^{-1}\left(\mathbb{E}_t[\bm{r}_{t+1}]-r_{0,t+1}\bm{\ell}+\frac{1}{2}\bm{\sigma}_t^2\right).(\#eq:Potmultalpha)
\end{equation}

Som igen er ækvivalent med den optimale løsning, Ligning \@ref(eq:Multalpha), for middelværdi-varians analysen i det multivariate tilfælde. På samme måde som i middelværdi-varians analysen, har løsningen egenskaben, at koefficienten for relativ risikoaversion, $\gamma$, kun påvirker den overordnede skalering af positionen i det risikobærende aktiv, men ikke kompositionen. Dette er ensbetydende med, at \textit{The Mutual Fund Seperation Theorem}, [@Tobin1958], også holder i den lognormale model med potens nytte. Et mere generelt tilfælde end ovenstående, er når der ikke eksisterer et risikofrit aktiv, og man da i stedet må benytte et risikobærende *benchmark*-afkast, $r_{b,t+1}$, da bliver løsningen
\begin{equation*}
\bm{\alpha}_t=\frac{1}{\gamma}\bm{\Sigma}^{-1}\left(\mathbb{E}_t[\bm{r}_{t+1}]-r_{b,t+1}\bm{\ell}+\frac{1}{2}\bm{\sigma}_t^2\right)+\left(1-\frac{1}{\gamma}\right)\left(-\bm{\Sigma}_t^{-1}\bm{\sigma}_{b,t}\right).
\end{equation*}

## Model for $k$-perioder {#modkper}
Analysen har indtil videre benyttet den restriktive antagelse, at investoren kun har en én-periodes investeringshorisont. Et mere realistisk tilfælde, er at antage, at investorens forventede nytte er udledt på baggrund af formuefordeling flere perioder fra nu. I flere-periode modellen, antages det, at afkast på investeringer bliver geninvesteret, dette implicerer den nye budgetbegrænsning
\begin{align*}
W_{t+k}&=R_{pk,t+k}W_t\\
&=R_{p,t+1}R_{p,t+2}\cdots R_{p,t+k}W_t.
\end{align*}

hvor $k$ er investeringshorisonten og $R_{pk,t+k}$ noterer det kumulative afkast over perioderne fra $t$ til $t+k$. Ved brug af log, kan det kumulative $k$-periode afkast simplificeres til summen af $k$ én-periode log afkast
\begin{equation}
r_{pk,t+k}=r_{p,t+1}+\cdots+r_{p,t+k}. (\#eq:sumportk)
\end{equation}

I de følgende sektioner vil flere specialtilfælde af det multiple-periode setup blive analyseret. Først tages hånd om tilfældet, hvor porteføljen på tidspunkt $t$ skal holdes i alle følgende perioder uden rebalancering.

### Uden periodisk rebalancering
I tilfældet uden periodisk rebalancering skal investoren evaluere $k$-periode afkastet, på samme måde som i tilfældet med én-periode. Udover antagelsen om lognormalitet og potens nytte, antages nu den restriktive betingelse, at alle aktivafkast er uafhængige og identisk fordelte over tid. Dette betyder, at det risikofrie $k$-periode logafkast er konstant lig $kr_{0}$, det $k$-periode forventede log afkast for de risikobærende aktiver er $k\mathbb{E}(\bm{r})$, kovariansmatricen af logafkastet på de risikobærende aktiver er konstant lig $\bm{\Sigma}$ og siden alle afkast er ukorrellerede bliver kovariansmatricen over en $k$-periode lig $k\bm{\Sigma}$. Givet at Taylor approksimationen, Ligning \@ref(eq:Multtaylor), er tilstrækkelig approksimerende for den givne respektive periode er løsningen, Ligning \@ref(eq:Potmultalpha), stadig optimal. Dette følger da alle middelværdier og kovarianserer bliver skaleret med den samme faktor, $k$
\begin{equation}
\bm{\alpha}_t=\frac{1}{\gamma}(k\bm{\Sigma})^{-1}\left(k\mathbb{E}_t[\bm{r}_{t+1}]-kr_{0,t+1}\bm{\ell}+\frac{1}{2}k\bm{\sigma}_t^2\right). (\#eq:Potmultalphak)
\end{equation}

Altså vil investoren vælge den samme portefølje over hele deres investeringshorisont givet, at der ikke er mulighed for periodisk rebalancering.

### Med periodisk rebalancering {#medperireb}
Antagelsen om, at ingen rebalancering finder sted over tid, synes at være i modstrid med virkelige observationer. Derfor arbejdes videre med en teoretisk ramme, som tillader periodisk rebalancering af investorporteføljen. Den første som beskrev maksimering af nytte ift. terminal formue var [@Mossin1968], som beskriver problemet i diskrettid. [@Mossin1968] noterede sig, at enhver følge af portefølje beslutninger skal være betingede af resultatet fra tidligere perioder, men på samme tid tage hensyn til information vedr. de fremtidige fordelinger af afkast. [@Samuelson1969] udvidede denne teori til at medtage forbrug, mens [@Merton1969; @Merton1971] beskrev en forbrugsbaseret model i kontinuert tid. I det følgende vil to eksempler med traktable løsninger blive præsenteret. Disse eksempler medfører, at investoren handler myopisk, selvom der er mulighed for rebalancering.

Først præsenteres den generelle potens nytte investor med *i.i.d.* afkast. Givet at investoren har potens nytte og at afkastene på aktiverne er *i.i.d.*, er det muligt at vise, at investorens porteføljevalg vil blive myopiske. Dette er også kendt som den første *Samuelson-Merton* betingelse. En intuitiv forklaring er som følger: Givet *i.i.d.* afkast vil investoren ikke opnå ny information vedr. log afkastfordelingen over tid. Dernæst haves at *RRA* er konstant, hvilket medfører at porteføljevalget er uafhængig af formueniveauet. Når forskellige porteføljestrategier, $\bm{\alpha}_t$ for $t=1,\dots,k$, tillades kan $2$-periode portefølje merafkastet omskrives til
\begin{align*}
r_{p2,t+2}-2r_0&=(r_{p,t+1}-r_0)+(r_{p,t+2}-r_0)\\
&= \bm{\alpha}_t'(\bm{r}_{t+1}-r_0\bm{\ell})+\frac{1}{2}\bm{\alpha}_t'\bm{\sigma}^2-\frac{1}{2} \bm{\alpha}_t'\bm{\Sigma}\bm{\alpha}_t + \bm{\alpha}_{t+1}'(\bm{r}_{t+2}-r_0\bm{\ell})+\frac{1}{2}\bm{\alpha}_{t+1}'\bm{\sigma}^2-\frac{1}{2} \bm{\alpha}_{t+1}'\bm{\Sigma}\bm{\alpha}_{t+1}
\end{align*}

Ovenstående kan generaliseres til $k$-perioder. Den betingede varians af $2$-periode log porteføljeafkastet bliver
$$\mathbb{V}_t[r_{p2,t+2}]=\bm{\alpha}_t'\bm{\Sigma}\bm{\alpha}_t+\bm{\alpha}_{t+1}'\bm{\Sigma}\bm{\alpha}_{t+1},$$

eftersom $\bm{\alpha}_{t+1}$ også fastsættes på tidspunkt $t$. Middelværdien af log porteføljeafkastet er
$$\mathbb{E}[r_{p2,t+2}]+\frac{1}{2}\mathbb{V}[r_{p2,t+2}]=2r_0 + (\bm{\alpha}_t'+\bm{\alpha}_{t+1}')(\mathbb{E}[r]-r_0\bm{\ell}+\frac{1}{2}\bm{\sigma}^2).$$

Benyttelse af ovenstående momenter giver følgende maksimeringsproblem for $2$-periode porteføljeproblemet med periodisk rebalancering
\begin{align}
&\max\mathbb{E}_t[r_{p2,t+2}] + \frac{1}{2} \mathbb{V}_t(r_{p2,t+2})-\frac{1}{2}\gamma \mathbb{V}_t[r_{p2,t+2}]\notag \\
&=2r_0+(\bm{\alpha}_t'+\bm{\alpha}_{t+1}')\left(\mathbb{E}[r]-r_0\bm{\ell}+\frac{1}{2}\bm{\sigma}^2\right)-\frac{1}{2}\gamma (\bm{\alpha}_t'\bm{\Sigma}\bm{\alpha}_t+\bm{\alpha}_{t+1}'\bm{\Sigma}\bm{\alpha}_{t+1})
(\#eq:CRRAmakslogk2periode)
\end{align}

Ovenstående medfører, at investorer med $\gamma>0$ vil vælge porteføljer med en lavere varians for et givet varians justeret forventet afkast. Men den justerede middelværdi afhænger kun af summen af de to vægte $(\bm{\alpha}_t'+\bm{\alpha}_{t+1}')$. Investorerne kan dermed justere de individuelle vægte og for den faste sum minimere variansen. I optimum vil variansen være minimeret ved at sætte $\bm{\alpha}_t=\bm{\alpha}_{t+1}$. Dette betyder, at ingen rebalancering er optimal på trods af muligheden i hver periode. Dette medfører altså, at den langsigtede investor handler myopisk, ***når*** afkastene på aktiverne er *i.i.d.* over tid. 

Den anden *Samuelson-Merton* betingelse som foranlediger til det myopiske porteføljevalg er baseret på faktummet, at en investor har log nytte, dvs. potens nytte, hvor $\gamma=1$. Her vil porteføljevalget være myopisk, uanset om aktiv afkastene er *i.i.d.* Argumenteret for dette er, at en log nytte investor vælger en portefølje, som maksimerer det forventede logafkast. Ligning \@ref(eq:sumportk) viser at $k$-periode log afkastet er summen af én-periode logafkast. Summen bliver maksimeret ved at maksimere hvert element seperat, siden at porteføljen frit kan blive valgt hver periode, altså vil hver én-periodes maksimering lede til det myopiske valg.

## Rekursiv løsning {#rekloes}

I forlængelse af ovenstående modeller følges nu den analytiske løsning til det dynamiske porteføljeproblem foreslået af [@JurVic2011]. Her betragtes en investor med initial formue $W_t$ på tidspunkt $t$, som vælger en porteføljestrategi, der maksimerer den forventede nytte af formue $k$ perioder frem i tiden, altså på tidspunkt $t+k$. Investoren antages at have potens nytte med konstant risikoaversions parameter, $\gamma$, og forbruger den akkumulerede nytte på terminaltidspunktet, $t+k$. 

Investoren vælger altså vægte sådan, at
\begin{align}
\left\{\bm{\alpha}_{t+k-\tau}^\tau\right\}_{\tau=k}^{\tau=1}=
\begin{cases}
\arg\max\mathbb{E}_t\left[\frac{1}{1-\gamma}W_{t+k}^{1-\gamma}\right],\quad &\gamma\neq 1\\
\arg\max\mathbb{E}_t\left[\log(W_{t+k})\right],\quad &\gamma=1.
\end{cases}(\#eq:jurvaegt)
\end{align}

Her er $\tau$ den resterende tid til investeringshorisonten. Altså indekseres vægtenes på det tidspunkt de bliver valgt med sænket skrift, og med hævet skrift for den resterende tid til investeringshorisonten. Risikopræferencen for investoren indebærer, at $(1+R_{p,t+i})>0$ for $i=1,\dots,k$. For de optimale vægte haves derfor
\begin{equation}
W_{t+k}=W_t\exp(r_{p,t\to t+k}),(\#eq:formuetk)
\end{equation}

hvor $r_{p,t\to t+k}=\sum_{i=1}^k r_{p,t+i}$ er $k$-periode log porteføljeafkastet mellem tidspunkt $t$ og $t+k$. Dette tillader, at vægtene \@ref(eq:jurvaegt), kan omskrives til
\begin{align}
\left\{\bm{\alpha}_{t+k-\tau}^\tau\right\}_{\tau=k}^{\tau=1}=\begin{cases}
\arg\max\mathbb{E}_t\left[\exp ((1-\gamma) r_{p,t\to t+k})\right],\quad &\gamma\neq 1\\
\arg\max\mathbb{E}_t\left[r_{p,t\to t+k}\right],\quad &\gamma=1.
\end{cases}(\#eq:jurvaegt2)
\end{align}

Som tidligere argumenteret vil en antagelse om rebalancering følge markedsobservationer, og det er ud fra denne antagelse, at [@JurVic2011] løser det generelle $k$-periode porteføljeproblem ved benyttelse af baglæns optrævling. Løsningen er en diskretiseret version af [@Liu2007], men mere fleksibel idet, at den kan håndtere et bredt spektrum af risikobærende aktiver og tilstandsvariable på samme tid. Derudover vil løsningen være eksakt i kontinuert tid, grundet den loglineære approksimation. Først udledes porteføljestrategien for den sidste periode, $\tau=1$, da denne vægtning vil danne grundlaget for resten af rekursionen. Den optimale portefølje for sidste periode er den sædvanlige myopiske eller én-periode middelværdi-varians optimale portefølje, som tidligere præsenteret
$$\bm{\alpha}_{t+k-1}^1=\frac{1}{\gamma}\bm{\Sigma}_{xx}^{-1}\left(\mathbb{E}_{t+k-1}\left[\bm{r}_{t+k}-r_{0,t+k}\bm{\ell}\right]+\frac{1}{2}\bm{\sigma}_x^2 + (1-\gamma) \bm{\sigma}_{0x}\right),$$

hvor, at
$$\mathbb{E}_{t+k-1}\left[\bm{r}_{t+k}-r_{0,t+k}\bm{\ell}\right]=\bm{H}_x(\bm{\Phi}_0 + \bm{\Phi}_1 \bm{z}_{t+k-1}),$$

og $\bm{H}_x$ er selektionsmatricen, som vælger rækkerne hørende til vektoren af merafkast $\bm{x}$ fra den relevante matrix. Den optimale portefølje kombinerer tangensporteføljen og global minimum varians porteføljen fra den efficiente rand, konstrueret af de én-periode forventede merafkast og kovariansmatricen af én-periode merafkastene. Tangensporteføljedelen er
$$\bm{\Sigma}_{xx}^{-1}\mathbb{E}_{t+k-1}\left[\bm{r}_{t+k}-r_{0,t+k}\bm{\ell}\right]+\frac{1}{2}\bm{\sigma}_x^2.$$

Denne portefølje er afhængig af de tidsvarierende merafkast og kovariansmatricen af merafkastene, dette er ensbetydende med at porteføljen vil ændre sig over tid. Global minimum varians porteføljen består af den anden del
$$\bm{\Sigma}_{xx}^{-1}\bm{\sigma}_{0x},$$

og afhænger kun af kovariansmatricen af merafkast, som forventet. Givet antagelsen om, at kovariansmatricen er konstant over tid, vil én-periode global minimum varians porteføljen ikke ændre sig over tid. Disse to porteføljedele vil investeren kombinere ved brug af hhv. $\tfrac{1}{\gamma}$ og $1-\tfrac{1}{\gamma}$, alt afhængig af *RRA*-parameteren $\gamma$. Log nytte investorer ($\gamma=1$) vil kun holde tangensporteføljen, mens investorer med højere og højere risikoaversion ($\gamma\to\infty$) kun vil holde global minimums varians porteføljen. Alle andre investorer vil bevæge sig mellem disse to yderpunkter.

Den generelle rekursive løsning til det dynamiske porteføljeproblem er givet ved
\begin{align}
\bm{\alpha}_{t+k-\tau}^\tau = &\frac{1}{\gamma} \bm{\Sigma}_{xx}^{-1} \left( \mathbb{E}_{t+k-\tau} \left[ \bm{r}_{t+k-\tau+1} - r_{0,t+k-\tau+1} \bm{\ell} \right] + \frac{1}{2} \bm{\sigma}_x^2 + (1-\gamma) \bm{\sigma}_{0x} \right) \notag\\
&- \left(1-\frac{1}{\gamma} \right) \bm{\Sigma}_{xx}^{-1} \bm{\Sigma}_x \left(B_1^{\tau-1'}+(B_2^{\tau-1}+B_3^{\tau-1'})\mathbb{E}_{t+k-\tau}[\bm{z}_{t+k-\tau+1}]\right),(\#eq:jurvicalpha)
\end{align}

hvor $\bm{\Sigma}_x=\begin{pmatrix}\bm{\sigma}_0x & \bm{\Sigma} & \bm{\Sigma}_{xs}'\end{pmatrix}$ og $B_1^{\tau-1}$, $B_2^{\tau-1}$ samt $B_3^{\tau-1}$ er funktioner afhængende af: den resterende investeringshorisont, $\tau$, *RRA*-parameteren, $\gamma$, samt koefficienterne fra VAR-modellen, [@JurVic2011]. Se Appendiks \@ref(optdynstrategi), for den fulde udledning.

Ovenstående Ligning \@ref(eq:jurvicalpha) giver den fulde analytiske løsning til det intertemporale porteføljeproblem fra Ligning \@ref(eq:jurvaegt2). Den optimale portefølje er en sum af to komponenter. Den første del af summen er identisk til den én-periode myopiske portefølje fra Ligning \@ref(eq:Potmultalpha). Den anden del af summen, består af det såkaldte *intertemporale hedging demand* for risikobærende aktiver, [@Merton1969; @Merton1971; @Merton1973]. Herudover viser løsningen, at den myopiske del af det totale porteføljevalg er uafhængigt af den resterende tid til investeringshorisonten, $\tau$. Den viser også at den myopiske del er den totale porteføljedel for investorer med log nytte, $\gamma=1$. Hvilket også er konsistent med intuitionen givet i Sektion \@ref(medperireb), at log nytte investorer ikke forholder sig til investeringshorisonten.

Komponentet som repræsenterer det *intertemporale hedging demand* er en funktion af *RRA*-koefficienten, koefficienterne fra VAR-systemet og koefficienterne af *value*-funktionen fra Appendiks \@ref(optdynstrategi), som selv er funktionern af koefficienterne fra VAR-systemet, og den tilbageværende investeringshorisont, $\tau$. Altså er det gennem det *intertemporale hedging demand*, at investeringshorisonten påvirker porteføljeallokeringen af den dynamiske rebalancerende investor.

En begrænsning af den analytiske løsning udledt ovenfor, er manglen på kortsalgs bibetingelser. Altså, hvordan porteføljevægtene vil være anderledes, givet at investoren står overfor en kortsalgsrestriktion. For at drage inferens om en kortsalgs restringeret investor laves en sammenlingning, hvor porteføljevægtene fra Ligning \@ref(eq:jurvicalpha) trunkeres givet, at de er negative. Herefter normaliseres så hele formuen benyttes. Nedenstående viser beregningen
\begin{equation}
\alpha_{i,t}=\frac{\max(0,\alpha_{i,t})}{\sum_{i=1}^n \max(0,\alpha_{i,t})}.(\#eq:kortsalgsrestr)
\end{equation}

På denne måde opnås en repræsentativ portefølje, som kan benyttes til at besvare spørgsmålet, hvordan porteføljebeslutingen ændrer sig, ifm. en kortsalgsrestriktion.

## Opsummering