# (APPENDIX) Appendiks {-} 

\part{Appendiks}

# Underliggende teoretiske resultater {#underligteo}

Dette appendiks består af statiske resultater og af udledninger for de anvendte resultater gennem afhandlingen. Notationen som anvendes følger den generelle præsenterede notation fra tidligere kapitler.

## Momenter af den lognormale fordeling {#momlognorm}

Det præsenterede porteføljevalg i den empiriske analyse tog udgangspunkt i en investor med potens nytte. Dette udmyntede sig i antagelsen om lognormale afkast. Lad en stokastisk variabel $Y=\exp(X)\sim \mathcal{LN}(\mu,\sigma^2)$ have den egenskab, at $X=\log(Y)\sim\mathcal{N}(\mu,\sigma^2)$. Da vil den forventede værdi af $Y$ være givet som
$$\mathbb{E}[Y]=\exp\left(\mu+\frac{1}{2}\sigma^2\right).$$

Variansen af $Y$ vil være givet ved
$$\mathbb{V}\left[Y\right]=\exp\left(2\mu+2\sigma^2\right)-\exp\left(2\mu+\sigma^2\right).$$

Det $n$'te moment af $Y$ kan skrives som
$$\mathbb{E}\left[Y^n\right]=\exp\left(n\mu + \frac{1}{2}n^2\sigma^2\right).$$

## Udledning af den optimale myopiske portefølje {#udlmyo}
I denne Sektion udledes den optimale portefølje på tidspunkt $t$ givet ved: Ligning \@ref(eq:Løsning) og Ligning \@ref(eq:Multalpha) for hhv. tilfældet med et risikobærende aktiv, $n=1$, samt tilfældet med flere risikobærende aktiver, $n>1$. Ved indsættelse af den betingede middelværdi, Ligning \@ref(eq:Forvport), samt den betingede varians, Ligning \@ref(eq:Varport). Kan Maksimeringsproblemet \@ref(eq:Statmaks) omskrives til
$$\max_{\alpha_t} \mathcal{L}=\alpha_t\left(R_{t+1} - R_{0,t+1}\right)-\frac{k}{2}\alpha_t^2\sigma_t^2.$$

I ovenstående er det ekstra led $R_{0,t+1}$ undladt idet, at det ikke ændrer maksimeringsproblemet.

Ved differentiation af ovenstående funktion, $\mathcal{L}(\cdot)$, mht. $\alpha_t$ opnås førsteordensbetingelsen
\begin{align*}
\frac{\partial \mathcal{L}}{\partial \alpha_t} &= \mathbb{E}_t\left[R_{t+1}\right] - R_{0,t+1} - \frac{k}{2}2\alpha\sigma_t^2=0\\
&\Updownarrow\\
\alpha&=\frac{\mathbb{E}_t\left[R_{t+1}\right]-R_{0,t+1}}{k\sigma_t^2}.
\end{align*}

Dermed er den optimale portefølje udledt, for tilfældet med ét risikobærende aktiv. For udledningen af den optimale portefølje på tidspunkt $t$ i tilfældet med flere risikobærende aktiver, differentieres funktionen, fra Maksimeringsproblemet \@ref(eq:MultStatmaks) mht. $\bm{\alpha}_t$, dermed fås
\begin{align*}
\frac{\partial \mathcal{L}}{\partial \bm{\alpha}_t} &= \left(\mathbb{E}_t\left[\bm{R}_{t+1}\right]- R_{0,t+1}\bm{\ell}\right) - \frac{k}{2}2\bm{\Sigma_t}\bm{\alpha}_t = 0\\
&\Updownarrow\\
\bm{\alpha}_t&=\frac{1}{k}\bm{\Sigma}_t^{-1}\left(\mathbb{E}_t\left[\bm{R}_{t+1}\right]-R_{0,t+1}\bm{\ell}\right).
\end{align*}

Her er de gængse regler for matrix differentiation og manipulation benyttet. 

## Udledning af *ARA* samt *RRA*
I denne Sektion udledes *Absolute Risk Aversion* samt *Relative Risk Aversion* målene for de tre præsenterede nyttefunktioner: kvadratisk nytte, eksponentiel nytte (*CARA*) og potens nytte (*CRRA*). Fælles for alle nyttefunktionerne er, at de er fuldstændigt defineret over formue.

### Kvadratisk nytte
For parametrene $a,b\in\mathbb{R}$ er kvadratisk nytte defineret som
\begin{equation*}
U(W_{t+1})=aW_{t+1}-bW_{t+1}^2.
\end{equation*}

*Absolute Risk Aversion* er defineret ved
$$\text{ARA}(W)=-\frac{U''(W)}{U'(W)}.$$

Altså vil kvadratisk nytte have følgende *ARA*
$$\text{ARA}_k(W_{t+1})=\frac{2b}{a-2bW_{t+1}},$$

hvor $k$ er notationen for kvadratisk. Fra ovenstående kan det ses, at *ARA* for kvadratisk nytte er stigende i $W_{t+1}$. Hvilket ikke er retsmæssigt, ift. den generelle holdning blandt emprisk litteratur. 

*Relative Risk Aversion* er defineret ved
$$\text{RRA}(W)=-\frac{WU''(W)}{U'(W)}.$$

Altså vil kvadratisk nytte have følgende *RRA*
$$\text{RRA}_k(W_{t+1})= \frac{2bW_{t+1}}{a-2bW_{t+1}}.$$

Endnu engang bemærkes det, at også *RRA* for kvadratisk nytte er stigende i $W_{t+1}$. 

### Eksponentiel nytte
Eksponentiel nytte betegnes undertiden *Constant Absolute Risk Aversion*. Eksponentiel nytte antager at variablene i modellen er normalfordelt. Lad $\theta\in\mathbb{R}$ være parametren i modellen, da vil eksponentiel nytte være defineret ved
\begin{equation*}
U(W_{t+1})=-\exp\left(-\theta W_{t+1}\right).
\end{equation*}

Eksponential nytte har følgende *ARA*
$$\text{ARA}_e(W_{t+1})=\frac{\theta^2\exp\left(-\theta W_{t+1}\right)}{\theta\exp\left(-\theta W_{t+1}\right)}=\theta,$$

hvor $e$ er notationen for eksponentiel. Fra ovenstående kan det ses, at *ARA* for eksponentiel nytte er konstant, som *CARA*-betegnelsen dækker over. Eksponentiel nytte har følgende *RRA*
$$\text{RRA}_e(W_{t+1})= \theta W_{t+1}.$$

Fra ovenstående ses det, at *RRA* for eksponentiel nytte er proportional til $W_{t+1}$.

### Potens nytte
Potens nytte kræver, at afkast af aktiverne og formue er lognormal fordelt. Potens nytte er bedre kendt under betegnelsen *Constant Relative Risk Aversion*. Lad parameteren $\gamma\in\mathbb{R}$ være givet, da er nyttefunktionen defineret for $W_{t+1}\geq 0$, som
$$U(W_{t+1})=\begin{cases} \frac{W_{t+1}^{1-\gamma}-1}{1-\gamma},\quad \gamma\neq 1\\
\log(W_{t+1}),\quad \gamma = 1. \end{cases}$$

Potens nytte har følgende *ARA*
$$\text{ARA}_p(W_{t+1})= \frac{\gamma W_{t+1}^{-\gamma-1}}{W_{t+1}^{-\gamma}}=\frac{\gamma}{W_{t+1}},$$

hvor $e$ er betegnelsen for eksponentiel. Det ses at *ARA* er faldende i $W_{t+1}$. Potens nytte har følgende *RRA*
$$\text{RRA}_p(W_{t+1})= \gamma,$$

som altså er konstant, dette ligger også til grund for *CRRA*-betegnelsen.

## Udledning af specialtilfældet for potens nytte
I denne Sektion udledes specialtilfældet af Ligning \@ref(eq:Potnytte), dvs. nyttefunktions form for risikoaversion, $\gamma$, lig $1$. Ved brug af *l'Hôpital's regel*. Reglen er defineret for to funktioner, $f(\cdot)$ og $g(\cdot)$, som er differentiable på et åbent interval $I$, undtagen for et fast punkt $c\in I$. Hvis
$$\lim_{x\to c} f(x)=\lim_{x\to c}g(x)=0\,\text{eller} \pm \infty,$$

samt
$$g'(x)\neq 0,\quad \forall X\in I,\,x\neq c$$

og grænsen
$$\lim_{x\to c} \frac{f'(x)}{g'(x)},$$

eksisterer, da gælder følgende lighed
$$\lim_{x\to c}\frac{f(x)}{g(x)}=\lim_{x\to c}\frac{f'(x)}{g'(x)}.$$

Altså kan der opnås et udtryk for grænsen, som kan evalueres. For $\gamma\rightarrow 1$ fås da
$$\lim_{\gamma\to 1}\frac{W_{t+1}^{1-\gamma}-1}{1-\gamma}=\lim_{\gamma\to 1}\frac{-W_{t+1}^{1-\gamma}\log\left(W_{t+1}\right)}{-1}=\log\left(W_{t+1}\right).$$

Dermed er tilfældet udledt.

## Loglinearisering af porteføljeafkastet
Investorens porteføljeafkast kan beskrives som
\begin{equation}
R_{p,t+1}-1 = \alpha_t(R_{t+1}- 1) + (1-\alpha_t)(R_{0,t+1}-1)=(R_{0,t+1} -1) + \alpha_t (R_{t+1} - R_{0,t+1}) (\#eq:logl1)
\end{equation}

Ligning \@ref(eq:logl1) kan omskrives til
\begin{equation}
\frac{R_{p,t+1}}{R_{0,t+1}} = 1 + \alpha_t \left(\frac{R_{t+1}}{R_{0,t+1}}-1\right), (\#eq:logl2)
\end{equation}

og ved samtidig transformation ved benyttelse af logfunktionen, opnås en ikke-lineær relation mellem log merafkastet på det risikobærende aktiv og log merafkastet på porteføljen
\begin{equation}
r_{p,t+1} - r_{0,t+1} = \log \left(1+\alpha_t (\exp(r_{t+1}-r_{0,t+1})-1)\right). (\#eq:logl3)
\end{equation}

Denne relation skaber problemerne i udledningen af porteføljeteorien, grundet dens ikke-linearitet. Som en approksimativ løsning kan en andenordens Taylor udvidelse omkring punktet, $r_{t+1}-r_{0,t+1}=0$, benyttes. Ovenstående relation defineres da nu $f_t(\cdot)$. Approksimationen bliver da
\begin{equation}
f_t(r_{t+1}-r_{0,t+1})\approx f_t(0) + f_t'(0)(r_{t+1}-r_{0,t+1})+\frac{1}{2}f_t''(0)(r_{t+1}-r_{0,t+1})^2. (\#eq:logl4)
\end{equation}

De afledte evalueret i centerpunktet er lig
\begin{align*}
f_t'(0) &= \alpha_t\\
f_t''(0) &= \alpha_t(1-\alpha_t).
\end{align*}

Derudover kan $(r_{t+1}-r_{0,t+1})^2$ erstattes med dens betingede forventning, der defineres som $\sigma_t^2$. Implementeres dette er Taylor approksimationen givet ved
\begin{equation}
r_{p,t+1} - r_{0,t+1} \approx \alpha_t(r_{t+1} - r_{0,t+1}) + \frac{1}{2} \alpha_t(1-\alpha_t)\sigma_t^2. (\#eq:logl5)
\end{equation}

Ligning \@ref(eq:logl5) kan let generaliseres til tilfældet med flere risikobærende aktiver, $n>1$. Denne generalisering vil føre til følgende approksimation
\begin{equation}
r_{p,t+1} - r_{0,t+1} \approx \bm{\alpha}_t'(\bm{r}_{t+1} - r_{0,t+1}\bm{\ell}) + \frac{1}{2} \bm{\alpha}_t'\bm{\sigma}_t^2 - \frac{1}{2}\bm{\alpha}_t'\bm{\Sigma}_t\bm{\alpha}_t. (\#eq:logl6)
\end{equation}

Her er de risikobærende aktiver lognormal fordelt med $\bm{\Sigma}_t$ som den betingede kovariansmatrix, og $\bm{\sigma}_t$ er diagonalelementerne af $\bm{\Sigma}_t$, som mere specifikt er vektoren af de betingede varianser for aktiverne.


# Campbell-Shiller loglineære relationer
De præsenterede loglineære af afkast følger en første ordens Taylor approksimation, og giver en analytisk løsning når diskrettidsmodeller benyttes. Fælles for alle aktivklasser er, at deres brutto afkast består af et ikke-lineært led som løses af følgende funktion
$$f(x)=f(x^*)+f'(x^*)(x-x^*).$$

## Approksimationen af aktieafkast

Den fundamentale relation mellem aktieafkast og udbytte udledes i denne sektion.

Definitionen af brutto aktieafkastet fra tidspunkt $t$ til $t+1$ er
\begin{equation}
1+R_{t+1}=\frac{P_{t+1}+D_{t+1}}{P_t}.
\end{equation}

Ved at tage logfunktionen af Ligning ?? kan følgende udledning opnås
\begin{align*}
\log\left(1+R_{t+1}\right)&=\log\left(\frac{P_{t+1}+D_{t+1}}{P_t}\right)\\
&=\log\left(P_{t+1}+D_{t+1}\right)-\log\left(P_t\right)\\
&=\log\left(P_{t+1}\left(1+\frac{D_{t+1}}{P_{t+1}}\right)\right)-\log\left(P_t\right)\\
&=\log\left(P_{t+1}\right)+\log\left(1+\exp\left(\log\left(D_{t+1}\right)-\log\left(P_{t+1}\right)\right)\right)-\log\left(P_t\right).
\end{align*}

Dette tillader følgende form ved brug af lognotationen
$$r_{t+1}=p_{t+1} +\log\left(1+\exp(d_{t+1}-p_{t+1})\right)-p_t$$

Ovenstående Ligning ?? viser den ikke-lineære relatioen mellem log afkastet og log udbyttet, altså er det andet led på højreside ikke-lineært, $\log\left(1+\exp(d_{t+1}-p_{t+1})\right)$. Ved brug af en første ordens Taylor udvidelse omkring middelværdien, $\overline{d_t-p_t}$, kan denne relation approksimeres. Herfra sættes $x=\log\left(1+\exp(d_{t+1}-p_{t+1})\right)$.

Her bliver den første afledte, $f'(x^*)$ fundet ved brug af kædereglen til
$$f'(x^*)=\frac{1}{1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)}\exp\left(\overline{d_{t+1}-p_{t+1}}\right).$$

Dermed bliver første ordens Taylor udvidelsen
\begin{align*}
f\left(x\right)&=\log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right)+\frac{1}{1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)}\\
\quad\quad&\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\left(\left(d_{t+1}-p_{t+1}\right)- \overline{d_{t+1}-p_{t+1}}\right).
\end{align*}

Ved at definere følgende lineariseringsparametre
\begin{align*}
\rho &=\frac{1}{1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)}\\
c&= \log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right) - \left(1-\rho\right)\left(\overline{d_{t+1}-p_{t+1}}\right),
\end{align*}

Kan $f\left(\log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right)\right)$ omskrives til
\begin{align*}
f\left(x\right)&=\log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right) + \rho\exp\left(\overline{d_{t+1}-p_{t+1}}\right) \left(d_{t+1}-p_{t+1}\right)\\
\quad\quad&-\rho \exp\left(\overline{d_{t+1}-p_{t+1}}\right)\left(\overline{d_{t+1}-p_{t+1}}\right)\\
&=\left(1-\rho\right)\left(d_{t+1}-p_{t+1}\right)+c.
\end{align*}

Indsættes Ligning ?? nu ind i Ligning ?? opnås den lineære relation for én-periode log aktieafkastet.

\begin{align*}
r_{t+1}&\approx p_{t+1} + \log\left(1+\exp\left(\overline{d_{t+1}-p_{t+1}}\right)\right)- p_t\\
&\approx p_{t+1} + \left(1-\rho\right) \left(d_{t+1}-p_{t+1}\right)- p_t + c\\
&\approx \rho p_{t+1} + \left(1-\rho\right) d_{t+1} - p_t + c.
\end{align*}

### Dynamic Gordon Growth Model

Identiteten fra *Dynamic Gordon Growth Model* findes fra Ligning ??, og ved indsættelse af $d_t-d_t$
\begin{align}
r_{t+1}&\approx \rho p_{t+1} + (1-\rho) d_{t+1} - p_t + c\\
&\approx \rho(p_{t+1}-d_{t+1})-d_{t+1}-p_t+c\\
&\approx \rho(p_{t+1}-d_{t+1})-d_{t+1}-p_t+d_t-d_t+c
\end{align}

Samles forskellen $\Delta d_{t+1}=d_{t+1}-d_t$, og løses dernæst for $d_t-p_t$, opnås
\begin{equation}
d_t-p_t=\rho (d_{t+1}-p_{t+1})+r_{t+1}-\Delta d_{t+1}-c.
\end{equation}

Tages nu den betingede forventning af Ligning ?? på tidspunkt $t$, og ved samtidig rekursion fås
\begin{align}
\mathbb{E}_t[d_t-p_t]&=\mathbb{E}_t[\rho(d_{t+1}-p_{t+1}) + r_{t+1} -\Delta d_{t+1}-c]\\
&=\mathbb{E}_t[\rho(\rho(d_{t+2}-p_{t+2}) + r_{t+2} -\Delta d_{t+2}-c) + r_{t+1} -\Delta d_{t+1} - c]\\
&\,\,\vdots\\
d_t-p_t&=\sum_{j=0}^\infty \rho^j \mathbb{E}_t[r_{t+j+1}-\Delta d_{t+j+1}] - \frac{c}{1-\rho}.
\end{align}

Hvor resultatet for en uendelig geometrisk række er anvendt samt transversalitetsbetingelsen, som udeholder økonomiske aktiebobler
$$\lim_{n\to\infty} \rho^n \mathbb{E}_t[d_{t+n} - p_{t+n}]=0.$$

Summationen starter ligeledes i nul for at fange det første led uden $\rho$.

## Approksimation af obligationsafkast

Rentespændet mellem en obligation med lang løbetid og en obligation med kort løbetid spiller en vigtig rolle på *Fixed Income* markedet. For at forstå rentespændet rolle, betragtes først et marked bestående af nulkupon obligationer. På tidspunkt $t$ er prisen for en $n$-periode obligation med effektiv rente $Y_t^n$ lig
\begin{equation}
P_t^n=\frac{1}{\left(1+Y_t^n\right)^n}.
\end{equation}

Tages logfunktionen på begge sider opnås
\begin{align}
\log\left(P_t^n\right)&=\log\left(\frac{1}{\left(1+Y_t^n\right)^n}\right)\\
&=-n\log\left(1+Y_t^n\right)\\
&=-n y_t^n\\
&\Updownarrow\\
y_t^n&=-\frac{1}{n}p_t^n.
\end{align}

Benyttes Ligning ?? følger det nu, at én-periode bruto afkastet på obligationen fra $t$ fra $t+1$ bliver
\begin{align}
1+R_{t+1}^n&=\frac{P_{t+1}^{n-1}}{P_t^n}\\
&=\frac{\frac{1}{\left(1+Y_t^n\right)^n}}{\frac{1}{\left(1+Y_t^{n-1}\right)^{n-1}}}.
\end{align}

Fra logresultatet opnås
\begin{align}
r_{t+1}^n&=p_{t+1}^{n-1}-p_t^n\\
&=n y_t^n - \left(n-1\right) y_{t+1}^{n-1}.
\end{align}

Dermed bliver den effektive rente på tidspunkt $t$ for en obligationen med $n$-perioder til udløb lig
\begin{align}
r_{t+1}^n&=n y_t^n - ny_{t+1}^{n-1}+y_{t+1}^{n-1}\\
&\Updownarrow\\
y_t^n &=\frac{1}{n}\left( r_{t+1}^n + (n-1) y_{t+1}^{n-1} \right).
\end{align}

Som $n$-periode obligationen bliver en $n-1$-periode obligation på tidspunkt $t+1$, ændres relationen til
\begin{align}
r_{t+2}^{n-1}&=\left(n-1\right) y_{t+1}^{n-1} - \left(n-2\right) y_{t+2}^{n-2}\\
&\Updownarrow\\
\left(n-1\right) y_{t+1}^{n-1}&=r_{t+2}^{n-1} + \left(n-2\right) y_{t+2}^{n-2}.
\end{align}

Fortsættes dette rul til én-periode før udløb, $t+n-1$, opnås 
\begin{equation}
y_{t+n-1}^{1}=\left(n-\left(n-1\right)\right)y_{t+n-1}^{n-\left(n-1\right)}=r_{t+n}^{n-\left(n-1\right)}=r_{t+n}^1.
\end{equation}

Kombineres Ligning ?? og implikationen for den effektive rente, for herefter at tage den betingede forventning, giver det gennemsnitlige afkast per periode, hvis obligationen holdes til udløb
\begin{align}
y_t^n&=\frac{1}{n} \left(r_{t+1}^n + r_{t+2}^{n-1}+\cdots+r_{t+n}^1\right)\\
&=\frac{1}{n}\sum_{i=0}^{n-1} r_{t+i+1}^{n-i}.
\end{align}

## Rentespændet

For at udlede rentespændet fratrækkes $y_t^1$ på begge sider af Ligning ??, så
\begin{align}
y_t^n-y_t^1&=\frac{1}{n} \sum_{i=0}^{n-1} \left(r_{t+i+1}^{n-i}-y_t^1\right)\\
&=\frac{1}{n} \sum_{i=0}^{n-1} \left(\left(y_{t+i}^1-y_t^1\right) + \left(r_{t+i+1}^{n-i}-y_t^1\right)\right).
\end{align}

Dermed kan det første led på højre side af summationen skrives som
\begin{align}
\sum_{i=0}^{n-1}\left(y_{t+i}^1-y_t^1\right)&=\left(y_{t+1}^1 y_t^1\right) + \left(y_{t+2}-y_t^1\right)+\dots +\left(y_{t+n-1} y_t^1\right)\\
&=\left(n-1\right)\Delta y_{t+1}^1+\left(n-2\right)\Delta y_{t+2}^1 + \dots+ \Delta y_{t+n-1}^1\\
&=\sum_{i=1}^{n-1}  \left(n-1\right)\Delta y_{t+i}^1.
\end{align}

Dette kan skrives i termer af rentespændet, $s_t^n=y_t^n-y_t^1$, ved at tage den betingede forventning på tidspunkt $t$, sådan at
\begin{equation}
s_t^n=\frac{1}{n} \sum_{i=1}^{n-1} \mathbb{E}_t[\left(n-1\right)\Delta y_{t+i}^1] + \frac{1}{n} \sum_{i=0}^{n-1} \mathbb{E}_t[\left(r_{t+i+1}^{n-i} - y_t^1\right)].
\end{equation}

## Varighed og renteimmunisering
[@Macaulay1938] viser at den negative elasticitet af en kuponobligations pris mht. brutto renten giver varigheden
\begin{equation}
D_t^{c,n} = -\frac{\text{d} P_t^{c,n}}{\text{d}\left(1+Y_t^{c,n}\right)}\frac{\left(1+Y_t^{c,n}\right)}{P_t^{c,n}},
\end{equation}

og er udledt gennem en andenordens Taylor approksimation
\begin{equation}
\frac{\text{d} P^{c,n}}{P^{c,n}}\approx \frac{\text{d} P^{c,n}}{\text{d} Y^{c,n}}\frac{\text{d} Y^{c,n}}{P^{c,n}}+\frac{1}{2}\frac{\text{d}^2 P^{c,n}}{\text{d} Y^{c,n,2}}\frac{\left(\text{d}Y^{c,n}\right)^2}{P^{c,n}},
\end{equation}

hvor den første afledte er den modificerede varighed og den anden afledte er konveksiteten af kuponobligationen, [@Campbell1997].

## Loglineær approksimation af kuponobligations afkast
På tidspunkt $t$ er afkastet på kuponobligationen med kuponbetaling $C$ lig
\begin{equation}
1+R_{t+1}^{c,n}=\frac{P_{t+1}^{c,n} + C}{P_t^{c,n}}.
\end{equation}

Tages logfunktionen på begge sider opnås
\begin{align}
\log\left(1+R_{t+1}^{c,n}\right)&=\\
&=\log\left(\frac{P_{t+1}^{c,n} + C}{P_t^{c,n}}\right)\\
&=\log\left(P_{t+1}^{c,n} + C\right) - \log\left(P_t^{c,n}\right)\\
r_{t+1}^{c,n}&=\log\left(1+\exp\left(c- p_{t+1}^{c,n}\right)\right) + p_{t+1}^{c,n} - p_t^{c,n}.
\end{align}

I ovenstående Ligning ??, er $\log\left(1+\exp\left(c- p_{t+1}^{c,n}\right)\right)$ ikke-lineær. For at løse dette anvendes en førsteordens Taylor approksimation omkring middelværdie, $\overline{c- p_{t+1}^{c,n}}$. Herfra sættes $x=\log\left(1+\exp\left(c- p_{t+1}^{c,n}\right)\right)$. 

Den første afledte, $f'\left(x^*\right)$, bliver fundet ved brug af kædereglen til
$$f'\left(x^*\right)=\frac{1}{1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)}\exp\left(\overline{c- p_{t+1}^{c,n}}\right).$$

Dermed bliver førsteordens Taylor approksimationen
\begin{align}
f\left(x\right)&=\log\left(1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)\right)+ \frac{1}{1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)}\exp\left(\overline{c- p_{t+1}^{c,n}}\right) \left(\left(c-p_{t+1}^{c,n}\right) -\left(\overline{c- p_{t+1}^{c,n}}\right)\right)\\
&=\log\left(1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)\right) + \frac{1}{1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)}\exp\left(\overline{c- p_{t+1}^{c,n}}\right) \left(c-p_{t+1}^{c,n}\right)\\
\quad&- \frac{1}{1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)}\exp\left(\overline{c- p_{t+1}^{c,n}}\right)\left(\overline{c- p_{t+1}^{c,n}}\right).
\end{align}

Defineres lineariseringsparameterne $k$ og $\rho$ til
\begin{align}
\rho&=\frac{1}{1+\exp\left(\overline{c- p_{t+1}^{c,n}}\right)}\\
k&=-\log\left(\rho\right)-\left(1-\rho\right)\log\left(\frac{1}{\rho-1}\right).
\end{align}

Kan der ved brug af rekursion opnås følgende resultat
\begin{equation}
p_t^{c,n}=\sum_{i=0}^{n-1} \rho^i\left(k+\left(1-\rho\right)c - r_{t+i+1}^{c,n-i}\right).
\end{equation}

Kombineres dette nu med approksimationen for log af den effektive rente, som opfylder
\begin{equation}
p_t^{c,n}\approx\sum_{i=0}^{n-1} \rho^i\left(k+\left(1-\rho\right)c - y_t^{c,n}\right).
\end{equation}

Kan den effektive rente af $n$-periode kuponobligationen udledes til
\begin{equation}
y_t^{c,n}\approx \left(\frac{1-\rho}{1-\rho^n}\right)\sum_{i=0}^{n-1}\rho^i r_{t+i+1}^{c,n-i}.
\end{equation}

Og ved substitution kan det approksimative loglinære afkast fra Kapitel ?? udledes.

# Den optimale dynamiske strategi {#optdynstrategi}
Dette appendiks vil udlede den optimale porteføljestrategi, som beskrevet i Sektion ??. Udledningen vil følge [@JurVic2011] Appendiks C, som beskriver metoden, med enkelte dele som varierer.

Uden tab af generalitet, kan det $k$-periode dynamiske porteføljeproblem løses, ved benyttelse af en rekursiv forlængelse af løsningen for optimalitetsproblemet hørende til de sidste to perioder. Først udledes porteføljestrategien i den sidste periode -- denne vil fungere som basis for den såkaldte *policy*-funktion i rekursionen -- samt den tilhørende *value* funktion. Herefter vil problemet i den foregående periode løses, dette problem er en funktion af koefficienterne fra *policy*- og *value*-funktionerne fra den sidste periode. Dette skaber det rekursive forhold mellem de to sidste tilstødende perioder, som herefter generalises til to generelle tilstødende perioder.

Investorens problem, i et to-periodes perspektiv, er at maksimere sin forventede nytte
\begin{align*}
\mathbb{E}_{t+k-2}\left[\frac{1}{1-\gamma} W_{t+k}^{1-\gamma}\right]&=\frac{1}{1-\gamma} W_{t+k-2}^{1-\gamma} \mathbb{E}_{t+k-2}\left[(1+R_{p,t+k-1})^{1-\gamma}(1+R_{p,t+k})^{1-\gamma}\right]\\
&=\frac{1}{1-\gamma} W_{t+k-2}^{1-\gamma} \mathbb{E}_{t+k-2}\left[\exp((1-\gamma) r_{p,t+k-1}) \mathbb{E}_{t+k-1}\left[\exp((1-\gamma)r_{p,t+k})\right]\right],
\end{align*}

ved at vælge følgen af vægte $\left\{\bm{\alpha}_{t+k-2}^2, \bm{\alpha}_{t+k-1}^1\right\}$. Variablene er indekseret med sænket skrift, som repræsenterer tidspunktet de bliver anvendt, og hævet skrift tid, der repræsenterer tid tilbage indtil investeringshorisonten.

## Tidspunkt $t+k-1$ ($\tau=1$)

### *Policy*-funktionen
Maksimeringsproblemet på tidspunkt $(t+k-1)$ er uændret ift. problemet som blev beskrevet ovenfor.
$$\max_{\bm{\alpha}_{t+k-1}^1} \mathbb{E}_{t+k-1}\left[\exp((1-\gamma)r_{p,t+k})\right] = \exp\left((1-\gamma) \mathbb{E}_{t+k-1}\left[r_{p,t+k}\right]+\frac{1}{2}(1-\gamma)^2 \mathbb{V}_{t+k-1}\left[r_{p,t+k}\right]\right).$$

Ved brug af selektionsmatricerne $\bm{H}_x$ og $\bm{H}_0$, er de første to momenter af porteføljeafkastet givet ved
\begin{align*}
\mathbb{E}_{t+k-1}\left[r_{p,t+k}\right]&= \bm{\alpha}_{t+k-1}^{1\prime} \bm{H}_x (\bm{\Phi}_0 +\bm{\Phi}_1\bm{z}_{t+k-1}) + \bm{H}_0(\bm{\Phi}_0 +\bm{\Phi}_1\bm{z}_{t+k-1})+\frac{1}{2} \bm{\alpha}_{t+k-1}^{1\prime} \left(\bm{\sigma}_x^2-\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-1}^{1}\right)\\
\mathbb{V}_{t+k-1}[r_{p,t+k}]&=\bm{\alpha}_{t+k-1}^{1\prime}\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-1}^{1}+ \sigma_0^2 + 2\bm{\alpha}_{t+k-1}^{1\prime}\bm{\sigma}_{0x}
\end{align*}

Den følgende førsteordensbetingelse, fremkommer efter substituion af ovenstående momenter ind i Maksimeringsproblemet ?? og dernæst første ordens differentiation 
$$\bm{H}_x\left(\bm{\Phi}_0 +\bm{\Phi}_1\bm{z}_{t+k-1}\right)+\frac{1}{2}\bm{\sigma}_x^2 - \bm{\Sigma}_{xx} \bm{\alpha}_{t+k-1}^{1}+\left(1-\gamma\right) \left(\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-1}^{1}+\bm{\sigma}_{0x}\right)=0.$$

Antages nu, at kovariansmatricen $\bm{\Sigma}_{xx}$ er ikke-singulær er ovenstående løst af
$$\bm{\alpha}_{t+k-1}^{1}=\frac{1}{\gamma}\bm{\Sigma}_{xx}^{-1}\left(\bm{H}_x(\bm{\Phi}_0 +\bm{\Phi}_1\bm{z}_{t+k-1})+\frac{1}{2}\bm{\sigma}_x^2+(1-\gamma) \bm{\sigma}_{0x}\right).$$

En nyttig omskrivning af den optimale portefølje, er at skrive den som en affin funktion af $\bm{z}_{t+k-1}$
\begin{equation}
\bm{\alpha}_{t+k-1}^{1} = A_0^1 + A_1^1\bm{z}_{t+k-1}, (\#eq:pol1p)
\end{equation}

hvor
\begin{align*}
A_0^1&=\frac{1}{\gamma} \bm{\Sigma}_{xx}^{-1}\left(\bm{\Phi}_0^x + \frac{1}{2}\bm{\sigma}_x^2+(1-\gamma)  \bm{\sigma}_{0x}\right)\\
A_1^1&=\frac{1}{\gamma} \bm{\Sigma}_{xx}^{-1}\bm{\Phi}_1^x.
\end{align*}

Dette afslutter udledningen for *policy*-funktionen på tidspunkt $(t+k-1)$.

### *Value*-funktionen
Udledningen for *value*-funktionen på tidspunkt $(t+k-1)$ startes med substitution af Ligning \@ref(eq:pol1p) ind i portefølje afkast momenterne. Dette gør, at de kan omskrives til funktioner af $A_i^1$ koefficienterne.
\begin{align*}
\mathbb{E}_{t+k-1}[r_{p,t+k}] &= \left(A_0^1 + A_1^1\bm{z}_{t+k-1}\right)' \left(\bm{\Phi}_0^x +\bm{\Phi}_1^x\bm{z}_{t+k-1}\right) + \left(\bm{\Phi}_0^0 +\bm{\Phi}_1^0 \bm{z}_{t+k-1}\right)\\
&\quad+\frac{1}{2} \left(A_0^1 + A_1^1\bm{z}_{t+k-1}\right)' \left(\bm{\sigma}_x^2-\bm{\Sigma}_{xx}\left(A_0^1 + A_1^1\bm{z}_{t+k-1}\right)\right)\\
&=\bm{\Phi}_0^0+ A_0^{1\prime} \left(\bm{\Phi}_0^x + \frac{1}{2} \left(\bm{\sigma}_x^2 - \bm{\Sigma}_{xx} A_0^1\right)\right) + \bm{z}_{t+k-1}' A_1^{1\prime} \left(\bm{\Phi}_0^x + \frac{1}{2} \left(\bm{\sigma}_x^2  - \bm{\Sigma}_{xx} A_0^1\right)\right)\\
&\quad+ \left(\bm{\Phi}_1^0 + A_0^{1\prime} \left(\bm{\Phi}_1^x - \frac{1}{2} \bm{\Sigma}_{xx} A_1^1\right)\right) \bm{z}_{t+k-1} +\bm{z}_{+k-1t}' A_1^{1\prime} \left(\bm{\Phi}_1^x - \frac{1}{2} \bm{\Sigma}_{xx} A_1^1\right) \bm{z}_{t+k-1}\\
\mathbb{V}_{t+k-1}[r_{p,t+k}]&=\left(A_0^1 + A_1^1\bm{z}_{t+k-1}\right)'\bm{\Sigma}_{xx}\left(A_0^1 + A_1^1\bm{z}_{t+k-1}\right)+ \bm{\sigma}_0^2 + 2\left(A_0^1 + A_1^1\bm{z}_{t+k-1}\right)'\bm{\sigma}_{0x}\\
&=\sigma_0^2 + A_0^{1\prime} \left(\bm{\Sigma}_{xx} A_0^1 + 2\bm{\sigma}_{0x}\right) + A_0^{1\prime}\bm{\Sigma}_{xx}A_1^1 \bm{z}_{t+k-1}\\
&\quad+\bm{z}_{t+k-1}' A_1^{1\prime} \left(\bm{\Sigma}_{xx} A_0^1 + 2\bm{\sigma}_{0x}\right) + \bm{z}_{t+k-1}' A_1^{1\prime} \bm{\Sigma}_{xx} A_1^1 \bm{z}_{t+k-1}.
\end{align*}

Siden hvert led i ovenstående summer er en skalar, kan ethvert komponent, i hvert led, frit udskiftes med dets transponerede. Dette medfører at leddene kan skrives ift. $\bm{z}_{t+k-1}$ og $\bm{z}_{t+k-1}'$. Indsættes ovenstående momenter nu i $(t+k-1)$ optimeringsfunktionen, opnås en forventning af en eksponentiel polynomisk funktion af tilstandsvektoren, som kan beregnes i lukket form, for at opnå den maksimerede *value*-funktion
$$\mathbb{E}_{t+k-1}\left[\exp((1-\gamma)r_{p,t+k}^*)\right] = \exp\left((1-\gamma) (B_0^1 + B_1^1 \bm{z}_{t+k-1}+\bm{z}_{t+k-1}'B_2^1 \bm{z}_{t+k-1})\right),$$

hvor
\begin{align*}
B_0^1&=\bm{\Phi}_0^0 + A_0^{1\prime} \left(\bm{\Phi}_0^x + \frac{1}{2} \bm{\sigma}_x^2\right) + \frac{1-\gamma}{2}\left(\sigma_0^2 + 2 A_0^{1\prime} \bm{\sigma}_{0x}\right) - \frac{\gamma}{2} A_0^{1\prime} \bm{\Sigma}_{xx} A_0^1\\
B_1^1&=\bm{\Phi}_1^0 + A_0^{1\prime}\left(\bm{\Phi}_1^x - \gamma \bm{\Sigma}_{xx} A_1^1\right) + \left(\bm{\Phi}_{0}^x + \frac{1}{2} \bm{\sigma}_x^2 + \left(1-\gamma\right)\bm{\sigma}_{0x}\right)' A_1^1\\
B_2^1&=A_1^{1\prime} \left(\bm{\Phi}_1^x - \frac{\gamma}{2} \bm{\Sigma}_{xx} A_1^1\right).
\end{align*}

## Tidspunkt $t+k-2$ ($\tau=2$)

### *Policy*-funktionen
Det næstsidste periode problem, $(t+k-2)$, involverer at vælge porteføljevægtene $\bm{\alpha}_{t+k-2}^2$, som maksimerer den følgende funktion
$$\frac{W_{t+k-2}^{1-\gamma}}{1-\gamma} \mathbb{E}_{t+k-2}\left[\exp\left(\left(1-\gamma\right) r_{p,t+k-1}\right) \exp\left(\left(1-\gamma\right) \left(B_0^1 + B_1^1 \bm{z}_{t+k-1} + \bm{z}_{t+k-1}' B_2^1\bm{z}_{t+k-1}\right)\right)\right]$$

Eftersom hverken $\tfrac{1}{1-\gamma}$ eller $W_{t+k-2}^{1-\gamma}$ påvirker optimum kan det fjernes fra optimeringsfunktionen. Ved brug af Taylor approksimationen, [@CampVicCha2003], kan $(t+k-1)$ log porteføljeafkastet beskrives som en funktion af $\bm{z}_{t+k-1}$. Dette tillader, at leddene kan samles i eksponentialet og derefter beregne forventningen. 

$(t+k-1)$ log porteføljeafkastet approksimeres ved
\begin{align*}
r_{p,t+k-1}&=\bm{\alpha}_{t+k-2}^{2\prime} + \bm{x}_{t+k-1} + r_{0,t+k-1} + \frac{1}{2} \bm{\alpha}_{t+k-2}^{2\prime} \left(\bm{\sigma}_x^2 - \bm{\Sigma}_{xx} \bm{\alpha}_{t+k-2}^{2}\right)\\
           &=\begin{pmatrix} 1 & \bm{\alpha}_{t+k-2}^{2} & \bm{0}\end{pmatrix} \bm{z}_{t+k-1} + \frac{1}{2}\bm{\alpha}_{t+k-2}^{2\prime} \left(\bm{\sigma}_x^2 - \bm{\Sigma}_{xx} \bm{\alpha}_{t+k-2}^{2}\right).
\end{align*}

Ved substition af ovenstående ind i $(t+k-2)$ optimeringsfunktionen fås
\begin{align*}
\mathbb{E}_{t+k-2}\Big[&\exp\Big(\Big(1-\gamma\Big)  \Big(\frac{1}{2}\bm{\alpha}_{t+k-2}^{2\prime} \Big(\bm{\sigma}_x^2 - \bm{\Sigma}_{xx} \bm{\alpha}_{t+k-2}^{2}\Big) + B_0^1 + \Big(B_1^1 + \begin{pmatrix} 1 & \bm{\alpha}_{t+k-2}^{2} & \bm{0}\end{pmatrix} \Big) \bm{z}_{t+k-1}\\
                   &+ \bm{z}_{t+k-1}'B_2^1 \bm{z}_{t+k-1} \Big)\Big)\Big].
\end{align*}

Fra ovenstående ses, at investoren på tidspunkt $(t+k-2)$ ved, at kun de sidste to summer i eksponentialet er stokastiske. Derfor fokusers, for nu, på at evaluere den følgende funktion, givet investorens valg af $\bm{\alpha}_{t+k-2}^{2}$
$$\mathbb{E}_{t+k-2}[ \exp\left( \left(1-\gamma\right) \left(\left(B_1^1 + \begin{pmatrix} 1 & \bm{\alpha}_{t+k-2}^{2} & \bm{0}\end{pmatrix} \right) \bm{z}_{t+k-1} + \bm{z}_{t+k-1}'B_2^1 \bm{z}_{t+k-1}  \right)\right) ].$$

Resultatet af denne beregning vil herefter substitueres ind i den oprindelige optimeringsfunktion, for at opnå forvetningen af *value*-funktionen betinget på investorens porteføljevalg, som herefter bliver maksimeret over $\bm{\alpha}_{t+k-2}^{2}$.

Fordelingen af $\bm{z}_{t+k-1}$ betinget på tidspunkt $(t+k-2)$-informationen er givet ved
$$\bm{z}_{t+k-1\mid t+k-2}\sim\mathcal{N}\left(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2},\bm{\Sigma}_v\right).$$

Dette betyder også at Ligning ?? beregner den forventede værdi af det eksponentielle kvadratiske polynomium i en normalfordelt stokastisk variabel.

For at lette notationen indføres nu de følgende hjælpevariable
\begin{align*}
C_1^2 &= (1-\gamma) \begin{pmatrix} 1\\ \bm{\alpha}_{t+k-2}^{2} \\ \bm{0} \end{pmatrix} + (1-\gamma) B_1^{1\prime}\\
C_2^2 &= (1-\gamma) B_2^1.
\end{align*}

Kombineres ovenstående hjælpevariable med Ligning ?? og den betingende fordeling af $\bm{z}_{t+k-1}$ fås
\begin{align*}
\mathbb{E}_{t+k-2}\Big[ \exp\Big( C_1^{2\prime} \bm{z}_{t+k-1} + \bm{z}_{t+k-1}' C_2^2 \bm{z}_{t+k-1} \Big) ] = &\mathbb{E}_{t+k-2}[ \exp \Big( C_1^{2\prime} \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} + \bm{v}_{t+k-2} \Big)\\
                                                                                                  &+ \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} + \bm{v}_{t+k-2}\Big)' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\\
                                                                                                  &+ \bm{v}_{t+k-2}\Big) \Big) \Big].
\end{align*}

Ovenstående Ligning ?? har led i eksponentialet, som enten er konstanter, lineære kombinationer af $\bm{v}_{t+k-2}$ stødene eller kvadratiske i $\bm{v}_{t+k-2}$. Derfor kan vi omarrangere leddene som følger
\begin{align*}
\mathbb{E}_{t+k-2}\Big[\exp\Big(\cdot\Big)\Big] &= \exp\Big( C_1^{2\prime} \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big) + \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)\Big)\\
                                &\,\,\quad \mathbb{E}_{t+k-2}\Big[\exp\Big( C_1^{2\prime} \bm{v}_{t+k-2}+ \bm{v}_{t+k-2}' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big) + \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)' C_2^{2} \bm{v}_{t+k-2}'\\
                                &\,\,\quad+ \bm{v}_{t+k-2}' C_2^2 \bm{v}_{t+k-2} \Big)\Big]\\
                                &= \exp\Big( C_1^{2\prime} \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big) + \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)\Big)\\
                                &\,\,\quad \mathbb{E}_{t+k-2}\Big[\exp\Big( C_1^{2\prime} \bm{v}_{t+k-2}+ \bm{v}_{t+k-2}' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big) + \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)' C_2^{2} \bm{v}_{t+k-2}'\Big)\\
                                &\,\,\quad\exp\Big(\bm{v}_{t+k-2}' C_2^2 \bm{v}_{t+k-2} \Big)\Big]\\
                                &=\exp\Big( C_1^{2\prime} \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big) + \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)\Big)\\
                                &\,\,\quad \mathbb{E}_{t+k-2}\Big[ \exp\Big(\bm{v}_{t+k-2}' C_2^2 \bm{v}_{t+k-2} \Big) \exp\Big( C_1^{2\prime} + 2\Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)' \Tilde{C}_2^{2} \Big)   \bm{v}_{t+k-2}\Big],
\end{align*}

hvor $\Tilde{C}_2^{2}$ er gennemsnittet af ikke-tilde-matricen og dens egen transponerede. Ved brug af dette sikres, at resultatet ikke er afhængig af symmetrien af de underliggende matricer. Hvis den underliggende matrix er symmetrisk vil tilde-notationen blive droppet, siden den underliggende matrix og tilde-matricen da vil være identiske.

Herfra er der to måder at evaluere ovenstående forventning: den komplementære approksimation og den eksakte evaluering. Den eksakte evaluering er først introduceret af [@CampVicCha2003]. Begge måder vil blive præsenteret, selvom de medfører empiriske resultater, som ikke er til at skelne mellem, [@JurVic2011]. 

#### Komplementær approksimation
Først beskrives den komplementære approksimation. Her bygger resultatet på, at alle led med orden højere end $\text{d}t$ har forsvindende sandsynlighed i grænsen, når tidsintervallet går mod nul. Altså vil kun de lineære led fra Ligning ?? være stokastiske. Altså er de lineære led af orden $\text{d}Z$, mens de kvadratiske led er af orden $\text{d}t$.
$$\lim_{\Delta t \to 0}\frac{\exp\left( \bm{v}_{t+k-2}' C_2^2 \bm{v}_{t+k-2} \right)}{\text{d}t}=\exp\left( \text{tr}\left(C_2^2 \bm{\Sigma}_v\right) \right).$$

Dette medfører at Ligning ?? simplificeres til
\begin{align*}
\lim_{\Delta t \to 0}\mathbb{E}_{t+k-2}\Big[\exp\Big(\cdot\Big)\Big] &=\exp\Big( C_1^{2\prime} \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big) + \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \Big)' C_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big) +  \text{tr}\Big(C_2^2 \bm{\Sigma}_v\Big)\Big)\\
                                &\,\,\quad \mathbb{E}_{t+k-2}\Big[ \exp\Big( C_1^{2\prime} + 2\Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)' \Tilde{C}_2^{2} \Big)   \bm{v}_{t+k-2}\Big],
\end{align*}

her observeres, at forventningen i Ligning ?? er forventningen af en lognormal stokastisk variabel, som er givet ved
\begin{align*}
\lim_{\Delta t \to 0}&\mathbb{E}_{t+k-2}\Big[ \exp\Big( C_1^{2\prime} + 2\Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)' \Tilde{C}_2^{2} \Big)   \bm{v}_{t+k-2}\Big]\\
&=\exp\Big(\frac{1}{2} \Big(C_1^{2\prime} + 2\Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)' \Tilde{C}_2^{2}\Big)' \bm{\Sigma}_v \Big(C_1^{2\prime} + 2\Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)' \Tilde{C}_2^{2}\Big)\Big) 
\end{align*}

Kombineres Ligning ?? og Ligning ?? ses, at Ligning ?? i grænsen for kontinuert tid er lig
\begin{align*}
\lim_{\Delta t \to 0} &\mathbb{E}_{t+k-2}\Big[ \exp\Big( C_1^{2\prime} \bm{z}_{t+k-1} + \bm{z}_{t+k-1}' C_2^2 \bm{z}_{t+k-1} \Big)\Big]\\
                      &=\exp\Big( \text{tr}\Big(C_2^2\bm{\Sigma}_v\Big) + D_0^{\Big(t+k-2\Big)} + \frac{1}{2} D_1^{\Big(t+k-2\Big)} \bm{\Sigma}_v^{-1} D_1^{\Big(t+k-2\Big)'} \Big),
\end{align*}

hvor
\begin{align*}
D_0^{\left(t+k-2\right)}&=C_1^{2\prime} \left(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \right) + \left(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2} \right)' C_2^2 \left(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\right) \\
D_1^{\left(t+k-2\right)}&=C_1^{2\prime} + 2\left(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\right)' \Tilde{C}_2^{2}.
\end{align*}

#### Eksakt evaluering
Ved brug af den eksakte evaluering foreslået af [@CampVicCha2003] er en løsning på lukket form stadig tilgengælig. Ved brug af den etablerede notation kan Ligning (46) fra det Tekniske Appendiks til [@CampVicCha2003] anvendes, for at opnå følgende evaluering af forventningen
\begin{align*}
&\mathbb{E}_{t+k-2}\left[ \exp\left( C_1^{2\prime} \bm{z}_{t+k-1} + \bm{z}_{t+k-1}' C_2^2 \bm{z}_{t+k-1} \right) \right]\\
&= \frac{\left| \bm{\Sigma}_v \right|^{-\tfrac{1}{2}}}{\left| \left(\bm{\Sigma}_v^{-1} - 2 D_2^{\left(t+k-2\right)}\right) \right|^{\tfrac{1}{2}}}\exp\left(D_0^{\left(t+k-2\right)} + \frac{1}{2} D_1^{\left(t+k-2\right)} \left(\bm{\Omega}^1\right)^{-1} D_1^{\left(t+k-2\right)\prime}\right),
\end{align*}

hvor følgende notation er introduceret
\begin{align*}
D_2^2&=C_2^2\\
\bm{\Omega}^1&=\left(\bm{\Sigma}_v^{-1} - 2D_2^2\right)^{-1}=\left(\bm{\Sigma}_v^{-1}  - 2\left(1-\gamma\right) B_2^1\right)^{-1}.
\end{align*}

#### Optimalt porteføljevalg {#optimportaer}
For et udlede den optimale portefølje strategi, droppes konstanten fra Ligning ??, siden dette ikke påvirker optimum. Altså ser investorens problem på tidspunkt $(t+k-2)$ således ud
$$\max_{\bm{\alpha}_{t+k-2}^2}\mathcal{L}= \left( \left(1-\gamma\right) \left(\frac{1}{2}\bm{\alpha}_{t+k-2}^{2\prime} \left(\bm{\sigma}_x^2 - \bm{\Sigma}_{xx}\bm{\alpha}_{t+k-2}^2\right) + B_0^1 + D_0^{\left(t+k-2\right)} + \frac{1}{2} D_1^{\left(t+k-2\right)} \bm{\Omega}^1 D_1^{\left(t+k-2\right)\prime}\right)\right).$$

Førsteordensbetingelsen bliver da
\begin{align*}
\frac{\partial \mathcal{L}}{\partial\bm{\alpha}_{t+k-2}^2 }&=\left(1-\gamma\right) \left(\bm{\Phi}_0^x+\bm{\Phi}_1^x\bm{z}_{t+k-2} + \frac{1}{2} \bm{\sigma}_x^2 -\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-2}^2 \right) + \frac{1}{2} \left(\frac{\partial D_1^{\left(t+k-2\right)\prime}}{\partial \bm{\alpha}_{t+k-2}^2}\right)' \left(\bm{\Omega}^1+\bm{\Omega}^{1\prime}\right) D_1^{\left(t+k-2\right)\prime}\\
                                                           &=\left(1-\gamma\right) \left(\bm{\Phi}_0^x+\bm{\Phi}_1^x\bm{z}_{t+k-2} + \frac{1}{2} \bm{\sigma}_x^2 -\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-2}^2 \right) + \left(\frac{\partial D_1^{\left(t+k-2\right)\prime}}{\partial \bm{\alpha}_{t+k-2}^2}\right)' \Tilde{\bm{\Omega}}^1 D_1^{\left(t+k-2\right)\prime} = 0.
\end{align*}

På baggrund af notationen for $D_1^2$ kan dens afledte mht. porteføljevægtene, $\bm{\alpha}_{t+k-2}^2$, relateres til de risikobærende merafkast aktivers selektions matrix
$$\frac{\partial D_1^{\left(t+k-2\right)\prime}}{\partial \bm{\alpha}_{t+k-2}^2} = \left(1-\gamma\right) \begin{pmatrix} \bm{0} \\ \bm{I}_{n-1} \\ \bm{0}\end{pmatrix}=\left(\frac{\partial D_1^{\left(t+k-2\right)\prime}}{\partial \bm{\alpha}_{t+k-2}^2}\right)' = \left(1-\gamma\right)\bm{H}_x.$$

Dette giver den følgende form for førsteordensbetingelsen
\begin{align*}
\frac{\partial \mathcal{L}}{\partial\bm{\alpha}_{t+k-2}^2 }&= \bm{\Phi}_0^x+\bm{\Phi}_1^x\bm{z}_{t+k-2}+\frac{1}{2} \bm{\sigma}_x^2 -\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-2}^2 +\bm{H}_x\Tilde{\bm{\Omega}}^{1}\Big(C_1^2+ 2\Tilde{C}_2^2 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)\Big)\\
&=\bm{\Phi}_0^x+\bm{\Phi}_1^x\bm{z}_{t+k-2}+\frac{1}{2} \bm{\sigma}_x^2 -\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-2}^2 + \Big(1-\gamma\Big)\Tilde{\bm{\Omega}}^{1} \Big(\begin{pmatrix} 1\\ \bm{\alpha}_{t+k-2}^2 \\ \bm{0} \end{pmatrix} + B_1^{1\prime}\\
&\quad + 2\Tilde{B}_2^1 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)\Big)\\
&=\bm{\Phi}_0^x+\bm{\Phi}_1^x\bm{z}_{t+k-2}+\frac{1}{2} \bm{\sigma}_x^2 -\bm{\Sigma}_{xx}\bm{\alpha}_{t+k-2}^2 + \Big(1-\gamma\Big)\Big(\Tilde{\bm{\Omega}}_{x0}^{1} + \Tilde{\bm{\Omega}}_{xx}^{1} \bm{\alpha}_{t+k-2}^2 + \Tilde{\bm{\Omega}}_{x} B_1^{1\prime}\\
&\quad + 2\Tilde{\bm{\Omega}}_{x}^1 \Tilde{B}_2^1 \Big(\bm{\Phi}_0+\bm{\Phi}_1\bm{z}_{t+k-2}\Big)\Big)\\
&=\Big(\Big(1-\gamma\Big)\Tilde{\bm{\Omega}}_{xx}^{1} - \bm{\Sigma}_{xx} \Big)  \bm{\alpha}_{t+k-2}^2 + \bm{\Phi}_0^x + \Big(1-\gamma\Big)\Big(\Tilde{\bm{\Omega}}_{x0}^{1} + \Tilde{\bm{\Omega}}_{x}^{1}\Big(B_1^{1\prime} + 2\Tilde{B}_2^{1}\bm{\Phi}_0\Big)\Big)+ \frac{1}{2} \bm{\sigma}_x^2\\
&\quad + \Big(\bm{\Phi}_1^x + 2\Big(1-\gamma\Big)\Tilde{\bm{\Omega}}_{x}^{1} \Tilde{B}_2^1\bm{\Phi}_1 \Big)\bm{z}_{t+k-2}=0.
\end{align*}

Løsningen til ovenstående førsteordensbetingelse medfører et udtryk for den optimale portefølje på tidspunkt $(t+k-2)$ som en affin funktion af $\bm{z}_{t+k-2}$
$$\bm{\alpha}_{t+k-2}^2 = A_0^2 + A_1^2 \bm{z}_{t+k-2},$$

hvor
\begin{align*}
A_0^2&=\left(\bm{\Sigma}_{xx} - \left(1-\gamma\right)\Tilde{\bm{\Omega}}_{xx}^1\right)^{-1} \left(\bm{\Phi}_0^x + \frac{1}{2} \bm{\sigma}_x^2 + \left(1-\gamma\right) \left(\Tilde{\bm{\Omega}}_{x0}^1 + \Tilde{\bm{\Omega}}_{x}^1 \left(B_1^{1\prime} + 2\Tilde{B}_2^{1}\bm{\Phi}_0\right)\right)\right)\\
A_1^2&=\left(\bm{\Sigma}_{xx} - \left(1-\gamma\right)\Tilde{\bm{\Omega}}_{xx}^1\right)^{-1}\left(\bm{\Phi}_1^x+2\left(1-\gamma\right) \Tilde{\bm{\Omega}}_{x}^1 \Tilde{B} _2^{1}\bm{\Phi}_1\right).
\end{align*}

På samme vis kan beregniner baseret på Ligning ??, give følgende resultat
\begin{align*}
A_0^2&=\frac{1}{\gamma} \bm{\Sigma}_{xx}^{-1} \left(\bm{\Phi}_0^x \frac{1}{2} \bm{\sigma}_x^2 + \left(1-\gamma \right) \left(\bm{\Sigma}_{x0} + \bm{\Sigma}_x \left(B_1^{1\prime} + 2\Tilde{B}_2^{1}\bm{\Phi}_0 \right)\right)\right)\\
A_1^2&=\frac{1}{\gamma} \bm{\Sigma}_{xx}^{-1} \left(\bm{\Phi}_1^x + 2\left(1-\gamma\right) \bm{\Sigma}_x \Tilde{B}_2^{1}\bm{\Phi}_1\right).
\end{align*}

Ligning ?? og Ligning ?? er identiske med Ligning ?? og Ligning ??, bortset fra at $\Tilde{\bm{\Omega}}^1$ er udskiftet med $\bm{\Sigma}_v$.

### *Value*-funktionen
Nu udledes de relevante udtryk for koefficienterne, $B_i^2$, i den maksimerede *value*-funktion. Dette gør, at der kan skabes et forhold mellem de foregående værdier af hhv. $A_i^1$ og $B_i^1$ koefficienterne. Ved indsættelse af den optimale porteføljeallokering for tidspunkt $\left(t+k-2\right)$ ind i *value*-funktionen, Ligning ??, og ved samtidig udeladelse af konstanter ganget på forventningen, opnås det følgende udtryk
\begin{align*}
&\mathbb{E}_{t+k-2}[ \exp\left( \left(1-\gamma\right)  r_{p,t+k-1}\right)\exp \left( \left(1-\gamma\right) \left(B_0^1 + B_1^1\bm{z}_{t+k-1}  + \bm{z}_{t+k-1}' B_2^1 \bm{z}_{t+k-1}  \right)\right)]\\
&=\exp\left(\left(1-\gamma\right)\left(\frac{1}{2}\bm{\alpha}_{t+k-2}^{2\prime} \left(\bm{\sigma}_x^2 - \bm{\Sigma}_{xx} \bm{\alpha}_{t+k-2}^2\right) + B_0^1 \right) + D_0^{\left(t+k-2\right)} + \frac{1}{2} D_1^{\left(t+k-2\right)} \bm{\Omega}^1 D_1^{\left(t+k-2\right)\prime}\right)\\
&=\exp\left(\left(1-\gamma\right)\left(B_0^2 + B_1^2 \bm{z}_{t+k-2} \bm{z}_{t+k-2}' B_2^2 \bm{z}_{t+k-2} \right)\right),
\end{align*}

hvor
\begin{align*}
B_0^2&=\bm{\Phi}_0^0 + A_0^{1\prime} \Big(\bm{\Phi}_0^x + \frac{1}{2}\bm{\sigma}_x^2\Big) + \frac{1-\gamma}{2} \Big(\bm{\Omega}_{00}^1 + 2A_0^{1\prime}\Tilde{\bm{\Omega}}_{x0}^1\Big)- \frac{1}{2} A_0^{1\prime} \Big(\bm{\Sigma}_{xx} - \Big(1-\gamma\Big) \bm{\Omega}_{xx}^1\Big) A_0^1 + B_0^1 \\
&\quad + \Big(B_1^1 + \bm{\Phi}_0' B_2^1\Big)\bm{\Phi}_0 + \Big(1-\gamma\Big) B_1^1 \Big(\Tilde{\bm{\Omega}}_1^{1\prime} + \frac{1}{2} \bm{\Omega}^1 B_1^{1\prime} + \Tilde{\bm{\Omega}}_x^{1\prime} A_0^1\Big)+ \Big(1-\gamma\Big) \bm{\Phi}_0' \Big(2\bm{\Lambda}^1 \bm{\Phi}_0 + \bm{\Xi}_1^{1\prime}\\
&\quad + \bm{\Xi}_x^{1\prime} A_0^1 + \bm{\Gamma}^1 B_1^{1\prime}\Big)\\
B_1^2&=\bm{\Phi}_1^1 + A_0^{1\prime} \Big(\bm{\Phi}_1^x - \Big(\bm{\Sigma}_{xx} - \Big(1-\gamma\Big) \Tilde{\bm{\Omega}}_{xx}^{1}\Big) A_1^1\Big) + \Big( \bm{\Phi}_0^x + \frac{1}{2} \bm{\sigma}_x^2 + \Big(1-\gamma\Big) \Tilde{\bm{\Omega}}_{x0}^{1}\Big)' A_1^1+ \Big(B_1^1 + 2\bm{\Phi}_0' \Tilde{B}_2^1\Big) \bm{\Phi}_1\\
&\quad + \Big(1-\gamma\Big) \Big(B_1^1 \Tilde{\bm{\Omega}}_{x}^{1\prime} + \bm{\Phi}_0' \bm{\Xi}_x^{1\prime}\Big) A_1^1 + \Big(1-\gamma\Big) \Big(4 \bm{\Phi}_0' \Tilde{\bm{\Lambda}}^1 + \bm{\Xi}_1^1 + A_0^{1\prime} \bm{\Xi}_x^1 + B_1^1 \bm{\Xi}^1\Big) \bm{\Phi}_1\\
B_2^2&= A_1^{1\prime} \Big(\bm{\Phi}_1^x - \frac{1}{2} \Big(\bm{\Sigma}_{xx} - \Big(1-\gamma\Big)\bm{\Omega}_{xx}^1\Big) A_1^1\Big) + \bm{\Phi}_1' \Big(B_2^1 + 2\Big(1-\gamma\Big) \bm{\Lambda}^1\Big) \bm{\Phi}_1 + \Big(1-\gamma\Big)\bm{\Phi}_1' \bm{\Xi}_x^{1\prime} A_1^1,
\end{align*}

hvor de følgende hjælpematricer er anvendt $\bm{\Lambda}^1=\Tilde{B}_2^{1}\bm{\Omega}^1 \Tilde{B}_2^{1\prime}$, $\bm{\Gamma}^1=2\Tilde{B}_2^{1}\Tilde{\bm{\Omega}}^1$ samt $\bm{\Xi}^1=\bm{\Gamma}^{1\prime}$.

I grænsen af kontinuert tid kan der ligeledes opnås simplificerede udtryk, analoge til trykkene, som ledte til udledning af *policy*-funktionen. Ergo bliver udtrykkene nu
\begin{align*}
B_0^2&=\bm{\Phi}_0^0 + A_0^{1\prime} \Big(\bm{\Phi}_0^x + \frac{1}{2}\bm{\sigma}_x^2\Big) + \frac{1-\gamma}{2} \Big(\bm{\Sigma}_{00}+ 2A_0^{1\prime} \bm{\Sigma}_{x0}\Big) - \frac{\gamma}{2} A_0^{1\prime} \bm{\Sigma}_{xx} A_0^1 + B_0^1 + \Big(B_1^1 + \bm{\Phi}_0' B_2^1\Big) \bm{\Phi }_0\\
&\quad + \Big(1-\gamma\Big)B_1^1 \Big(\bm{\Sigma}_0' + \frac{1}{2} \bm{\Sigma} B_1^{1\prime} + \bm{\Sigma}_x' A_0^1\Big) + \Big(1-\gamma\Big) \bm{\Phi}_0' \Big(2\bm{\Lambda}^1 \bm{\Phi}_0 + \bm{\Xi}_0^{1\prime} + \bm{\Xi}_x^{1\prime} A_0^1 + \bm{\Gamma}^1 B_1^{1\prime}\Big)\\
B_1^2&=\bm{\Phi}_1^1 + A_0^{1\prime} \Big(\bm{\Phi}_1^x -\gamma\bm{\Sigma}_{xx}\Big) A_1^1 + \Big(\bm{\Phi}_0^x + \frac{1}{2}\bm{\sigma}_x^2 + \Big(1-\gamma\Big) \bm{\Sigma}_{x0}\Big)' A_1^1 + \Big(B_1^1 + 2\bm{\Phi}_0' \Tilde{B}_2^1\Big)\bm{\Phi}_1 + \Big(1-\gamma\Big) \Big(B_1^1\bm{\Sigma}_x'\\
&\quad + \bm{\Phi}_0' \bm{\Xi}_{x}^{1\prime}\Big) A_1^1 + \Big(1-\gamma\Big) \Big(4 \bm{\Phi}_0' \Tilde{\bm{\Lambda}}^1 + \bm{\Xi}_1^1 + A_0^{1\prime} \bm{\Xi}_x^1 + B_1^1 \bm{\Xi}^1\Big)\bm{\Phi}_1,\\
B_2^2&= A_1^{1\prime} \Big(\bm{\Phi}_1^x - \frac{\gamma}{2} \bm{\Sigma}_{xx} A_1^1\Big) + \bm{\Phi}_1' \Big(B_2^1 + 2\Big(1-\gamma\Big) \bm{\Lambda}^1\Big) \bm{\Phi}_1 + \Big(1-\gamma\Big) \bm{\Phi}_1' \bm{\Xi}_x^{1\prime} A_1^1,
\end{align*}

hvor de følgende hjælpematricer er anvendt $\bm{\Lambda}^1=\Tilde{B}_2^{1}\bm{\Sigma}_v \Tilde{B}_2^{1\prime}$, $\bm{\Gamma}^1=2\Tilde{B}_2^{1}\bm{\Sigma}_v$ samt $\bm{\Xi}^1=\bm{\Gamma}^{1\prime}$.

Sammenhængen mellem *policy*-funktionen og *value*-funktionen i to succesive perioder er nu skabet, den generelle løsning kan blive opnået ved følgende udskiftninger
\begin{equation*}
1\to \tau-1\quad\text{og}\quad 2\to \tau-2.
\end{equation*}
